// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_FLUTTER_ZEBRA_BARCODE_G_H_
#define PIGEON_FLUTTER_ZEBRA_BARCODE_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>
#include <utility>
#include <variant>

namespace flutter_zebra_barcode {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class FlutterZebraBarcode;
  friend class FlutterZebraBarcodeCallbacks;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class ScannerConnectionType {
  kBluetooth = 0,
  kUsb = 1
};

enum class ScannerConnectionStatus {
  kConnecting = 0,
  kConnected = 1,
  kDisconnecting = 2,
  kDisconnected = 3,
  kError = 4
};

enum class BarcodeScannerSource {
  kBuiltInTerminal = 0,
  kRfidSled = 1,
  kExternalBluetooth = 2,
  kExternalUsb = 3,
  kUnknown = 4
};

enum class BarcodeScannerMode {
  kAuto = 0,
  kDataWedge = 1,
  kScannerSdk = 2
};


// Generated class from Pigeon that represents data sent in messages.
class BarcodeScanner {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit BarcodeScanner(int64_t id);

  // Constructs an object setting all fields.
  explicit BarcodeScanner(
    const std::string* name,
    int64_t id,
    const std::string* model,
    const std::string* serial_number);

  const std::string* name() const;
  void set_name(const std::string_view* value_arg);
  void set_name(std::string_view value_arg);

  int64_t id() const;
  void set_id(int64_t value_arg);

  const std::string* model() const;
  void set_model(const std::string_view* value_arg);
  void set_model(std::string_view value_arg);

  const std::string* serial_number() const;
  void set_serial_number(const std::string_view* value_arg);
  void set_serial_number(std::string_view value_arg);


 private:
  static BarcodeScanner FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FlutterZebraBarcode;
  friend class FlutterZebraBarcodeCallbacks;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> name_;
  int64_t id_;
  std::optional<std::string> model_;
  std::optional<std::string> serial_number_;

};


// Generated class from Pigeon that represents data sent in messages.
class Barcode {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit Barcode(
    const std::string& data,
    int64_t scanner_id);

  // Constructs an object setting all fields.
  explicit Barcode(
    const std::string& data,
    int64_t scanner_id,
    const int64_t* barcode_type,
    const std::string* endpoint_id,
    const BarcodeScannerSource* source,
    const std::string* scanner_name);

  const std::string& data() const;
  void set_data(std::string_view value_arg);

  int64_t scanner_id() const;
  void set_scanner_id(int64_t value_arg);

  const int64_t* barcode_type() const;
  void set_barcode_type(const int64_t* value_arg);
  void set_barcode_type(int64_t value_arg);

  const std::string* endpoint_id() const;
  void set_endpoint_id(const std::string_view* value_arg);
  void set_endpoint_id(std::string_view value_arg);

  const BarcodeScannerSource* source() const;
  void set_source(const BarcodeScannerSource* value_arg);
  void set_source(const BarcodeScannerSource& value_arg);

  const std::string* scanner_name() const;
  void set_scanner_name(const std::string_view* value_arg);
  void set_scanner_name(std::string_view value_arg);


 private:
  static Barcode FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FlutterZebraBarcode;
  friend class FlutterZebraBarcodeCallbacks;
  friend class PigeonInternalCodecSerializer;
  std::string data_;
  int64_t scanner_id_;
  std::optional<int64_t> barcode_type_;
  std::optional<std::string> endpoint_id_;
  std::optional<BarcodeScannerSource> source_;
  std::optional<std::string> scanner_name_;

};


// Generated class from Pigeon that represents data sent in messages.
class BarcodeScannerEndpoint {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit BarcodeScannerEndpoint(
    const std::string& endpoint_id,
    const std::string& display_name,
    const BarcodeScannerSource& source,
    const BarcodeScannerMode& mode,
    const ScannerConnectionStatus& connection_status,
    bool active,
    bool preferred);

  // Constructs an object setting all fields.
  explicit BarcodeScannerEndpoint(
    const std::string& endpoint_id,
    const std::string& display_name,
    const BarcodeScannerSource& source,
    const BarcodeScannerMode& mode,
    const ScannerConnectionStatus& connection_status,
    bool active,
    bool preferred,
    const std::string* zebra_scanner_identifier,
    const int64_t* scanner_index,
    const int64_t* scanner_id,
    const std::string* model,
    const std::string* serial_number);

  const std::string& endpoint_id() const;
  void set_endpoint_id(std::string_view value_arg);

  const std::string& display_name() const;
  void set_display_name(std::string_view value_arg);

  const BarcodeScannerSource& source() const;
  void set_source(const BarcodeScannerSource& value_arg);

  const BarcodeScannerMode& mode() const;
  void set_mode(const BarcodeScannerMode& value_arg);

  const ScannerConnectionStatus& connection_status() const;
  void set_connection_status(const ScannerConnectionStatus& value_arg);

  bool active() const;
  void set_active(bool value_arg);

  bool preferred() const;
  void set_preferred(bool value_arg);

  const std::string* zebra_scanner_identifier() const;
  void set_zebra_scanner_identifier(const std::string_view* value_arg);
  void set_zebra_scanner_identifier(std::string_view value_arg);

  const int64_t* scanner_index() const;
  void set_scanner_index(const int64_t* value_arg);
  void set_scanner_index(int64_t value_arg);

  const int64_t* scanner_id() const;
  void set_scanner_id(const int64_t* value_arg);
  void set_scanner_id(int64_t value_arg);

  const std::string* model() const;
  void set_model(const std::string_view* value_arg);
  void set_model(std::string_view value_arg);

  const std::string* serial_number() const;
  void set_serial_number(const std::string_view* value_arg);
  void set_serial_number(std::string_view value_arg);


 private:
  static BarcodeScannerEndpoint FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FlutterZebraBarcode;
  friend class FlutterZebraBarcodeCallbacks;
  friend class PigeonInternalCodecSerializer;
  std::string endpoint_id_;
  std::string display_name_;
  BarcodeScannerSource source_;
  BarcodeScannerMode mode_;
  ScannerConnectionStatus connection_status_;
  bool active_;
  bool preferred_;
  std::optional<std::string> zebra_scanner_identifier_;
  std::optional<int64_t> scanner_index_;
  std::optional<int64_t> scanner_id_;
  std::optional<std::string> model_;
  std::optional<std::string> serial_number_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class FlutterZebraBarcode {
 public:
  FlutterZebraBarcode(const FlutterZebraBarcode&) = delete;
  FlutterZebraBarcode& operator=(const FlutterZebraBarcode&) = delete;
  virtual ~FlutterZebraBarcode() {}
  // Returns list with names of available readers for specified `connectionType`.
  virtual void UpdateAvailableScanners(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Connects to a reader with `readerId` ID.
  virtual void ConnectScanner(
    int64_t scanner_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Disconnects a current scanner.
  virtual void DisconnectScanner(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Refreshes all barcode scanner endpoints, including DataWedge-managed
  // terminal scanners and Scanner SDK external scanners where available.
  virtual void RefreshBarcodeScanners(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Selects the endpoint that should be treated as the active barcode source.
  virtual void SetActiveBarcodeScanner(
    const std::string& endpoint_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Clears the explicit active barcode source.
  virtual void ClearActiveBarcodeScanner(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Reader currently in use
  virtual ErrorOr<std::optional<BarcodeScanner>> CurrentScanner() = 0;
  // Barcode scanner endpoint currently selected, if any.
  virtual ErrorOr<std::optional<BarcodeScannerEndpoint>> ActiveBarcodeScanner() = 0;

  // The codec used by FlutterZebraBarcode.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `FlutterZebraBarcode` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    FlutterZebraBarcode* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    FlutterZebraBarcode* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  FlutterZebraBarcode() = default;

};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class FlutterZebraBarcodeCallbacks {
 public:
  FlutterZebraBarcodeCallbacks(flutter::BinaryMessenger* binary_messenger);
  FlutterZebraBarcodeCallbacks(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnAvailableScannersChanged(
    const flutter::EncodableList& readers,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnAvailableBarcodeScannersChanged(
    const flutter::EncodableList& endpoints,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnActiveBarcodeScannerChanged(
    const BarcodeScannerEndpoint* endpoint,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnScannerConnectionStatusChanged(
    const ScannerConnectionStatus& status,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnBarcodeRead(
    const Barcode& barcode,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace flutter_zebra_barcode
#endif  // PIGEON_FLUTTER_ZEBRA_BARCODE_G_H_
