// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "flutter_zebra_barcode.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace flutter_zebra_barcode {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// BarcodeScanner

BarcodeScanner::BarcodeScanner(int64_t id)
 : id_(id) {}

BarcodeScanner::BarcodeScanner(
  const std::string* name,
  int64_t id,
  const std::string* model,
  const std::string* serial_number)
 : name_(name ? std::optional<std::string>(*name) : std::nullopt),
    id_(id),
    model_(model ? std::optional<std::string>(*model) : std::nullopt),
    serial_number_(serial_number ? std::optional<std::string>(*serial_number) : std::nullopt) {}

const std::string* BarcodeScanner::name() const {
  return name_ ? &(*name_) : nullptr;
}

void BarcodeScanner::set_name(const std::string_view* value_arg) {
  name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void BarcodeScanner::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


int64_t BarcodeScanner::id() const {
  return id_;
}

void BarcodeScanner::set_id(int64_t value_arg) {
  id_ = value_arg;
}


const std::string* BarcodeScanner::model() const {
  return model_ ? &(*model_) : nullptr;
}

void BarcodeScanner::set_model(const std::string_view* value_arg) {
  model_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void BarcodeScanner::set_model(std::string_view value_arg) {
  model_ = value_arg;
}


const std::string* BarcodeScanner::serial_number() const {
  return serial_number_ ? &(*serial_number_) : nullptr;
}

void BarcodeScanner::set_serial_number(const std::string_view* value_arg) {
  serial_number_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void BarcodeScanner::set_serial_number(std::string_view value_arg) {
  serial_number_ = value_arg;
}


EncodableList BarcodeScanner::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(name_ ? EncodableValue(*name_) : EncodableValue());
  list.push_back(EncodableValue(id_));
  list.push_back(model_ ? EncodableValue(*model_) : EncodableValue());
  list.push_back(serial_number_ ? EncodableValue(*serial_number_) : EncodableValue());
  return list;
}

BarcodeScanner BarcodeScanner::FromEncodableList(const EncodableList& list) {
  BarcodeScanner decoded(
    list[1].LongValue());
  auto& encodable_name = list[0];
  if (!encodable_name.IsNull()) {
    decoded.set_name(std::get<std::string>(encodable_name));
  }
  auto& encodable_model = list[2];
  if (!encodable_model.IsNull()) {
    decoded.set_model(std::get<std::string>(encodable_model));
  }
  auto& encodable_serial_number = list[3];
  if (!encodable_serial_number.IsNull()) {
    decoded.set_serial_number(std::get<std::string>(encodable_serial_number));
  }
  return decoded;
}

// Barcode

Barcode::Barcode(
  const std::string& data,
  int64_t scanner_id)
 : data_(data),
    scanner_id_(scanner_id) {}

Barcode::Barcode(
  const std::string& data,
  int64_t scanner_id,
  const int64_t* barcode_type,
  const std::string* endpoint_id,
  const BarcodeScannerSource* source,
  const std::string* scanner_name)
 : data_(data),
    scanner_id_(scanner_id),
    barcode_type_(barcode_type ? std::optional<int64_t>(*barcode_type) : std::nullopt),
    endpoint_id_(endpoint_id ? std::optional<std::string>(*endpoint_id) : std::nullopt),
    source_(source ? std::optional<BarcodeScannerSource>(*source) : std::nullopt),
    scanner_name_(scanner_name ? std::optional<std::string>(*scanner_name) : std::nullopt) {}

const std::string& Barcode::data() const {
  return data_;
}

void Barcode::set_data(std::string_view value_arg) {
  data_ = value_arg;
}


int64_t Barcode::scanner_id() const {
  return scanner_id_;
}

void Barcode::set_scanner_id(int64_t value_arg) {
  scanner_id_ = value_arg;
}


const int64_t* Barcode::barcode_type() const {
  return barcode_type_ ? &(*barcode_type_) : nullptr;
}

void Barcode::set_barcode_type(const int64_t* value_arg) {
  barcode_type_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void Barcode::set_barcode_type(int64_t value_arg) {
  barcode_type_ = value_arg;
}


const std::string* Barcode::endpoint_id() const {
  return endpoint_id_ ? &(*endpoint_id_) : nullptr;
}

void Barcode::set_endpoint_id(const std::string_view* value_arg) {
  endpoint_id_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void Barcode::set_endpoint_id(std::string_view value_arg) {
  endpoint_id_ = value_arg;
}


const BarcodeScannerSource* Barcode::source() const {
  return source_ ? &(*source_) : nullptr;
}

void Barcode::set_source(const BarcodeScannerSource* value_arg) {
  source_ = value_arg ? std::optional<BarcodeScannerSource>(*value_arg) : std::nullopt;
}

void Barcode::set_source(const BarcodeScannerSource& value_arg) {
  source_ = value_arg;
}


const std::string* Barcode::scanner_name() const {
  return scanner_name_ ? &(*scanner_name_) : nullptr;
}

void Barcode::set_scanner_name(const std::string_view* value_arg) {
  scanner_name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void Barcode::set_scanner_name(std::string_view value_arg) {
  scanner_name_ = value_arg;
}


EncodableList Barcode::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(EncodableValue(data_));
  list.push_back(EncodableValue(scanner_id_));
  list.push_back(barcode_type_ ? EncodableValue(*barcode_type_) : EncodableValue());
  list.push_back(endpoint_id_ ? EncodableValue(*endpoint_id_) : EncodableValue());
  list.push_back(source_ ? CustomEncodableValue(*source_) : EncodableValue());
  list.push_back(scanner_name_ ? EncodableValue(*scanner_name_) : EncodableValue());
  return list;
}

Barcode Barcode::FromEncodableList(const EncodableList& list) {
  Barcode decoded(
    std::get<std::string>(list[0]),
    list[1].LongValue());
  auto& encodable_barcode_type = list[2];
  if (!encodable_barcode_type.IsNull()) {
    decoded.set_barcode_type(encodable_barcode_type.LongValue());
  }
  auto& encodable_endpoint_id = list[3];
  if (!encodable_endpoint_id.IsNull()) {
    decoded.set_endpoint_id(std::get<std::string>(encodable_endpoint_id));
  }
  auto& encodable_source = list[4];
  if (!encodable_source.IsNull()) {
    decoded.set_source(std::any_cast<const BarcodeScannerSource&>(std::get<CustomEncodableValue>(encodable_source)));
  }
  auto& encodable_scanner_name = list[5];
  if (!encodable_scanner_name.IsNull()) {
    decoded.set_scanner_name(std::get<std::string>(encodable_scanner_name));
  }
  return decoded;
}

// BarcodeScannerEndpoint

BarcodeScannerEndpoint::BarcodeScannerEndpoint(
  const std::string& endpoint_id,
  const std::string& display_name,
  const BarcodeScannerSource& source,
  const BarcodeScannerMode& mode,
  const ScannerConnectionStatus& connection_status,
  bool active,
  bool preferred)
 : endpoint_id_(endpoint_id),
    display_name_(display_name),
    source_(source),
    mode_(mode),
    connection_status_(connection_status),
    active_(active),
    preferred_(preferred) {}

BarcodeScannerEndpoint::BarcodeScannerEndpoint(
  const std::string& endpoint_id,
  const std::string& display_name,
  const BarcodeScannerSource& source,
  const BarcodeScannerMode& mode,
  const ScannerConnectionStatus& connection_status,
  bool active,
  bool preferred,
  const std::string* zebra_scanner_identifier,
  const int64_t* scanner_index,
  const int64_t* scanner_id,
  const std::string* model,
  const std::string* serial_number)
 : endpoint_id_(endpoint_id),
    display_name_(display_name),
    source_(source),
    mode_(mode),
    connection_status_(connection_status),
    active_(active),
    preferred_(preferred),
    zebra_scanner_identifier_(zebra_scanner_identifier ? std::optional<std::string>(*zebra_scanner_identifier) : std::nullopt),
    scanner_index_(scanner_index ? std::optional<int64_t>(*scanner_index) : std::nullopt),
    scanner_id_(scanner_id ? std::optional<int64_t>(*scanner_id) : std::nullopt),
    model_(model ? std::optional<std::string>(*model) : std::nullopt),
    serial_number_(serial_number ? std::optional<std::string>(*serial_number) : std::nullopt) {}

const std::string& BarcodeScannerEndpoint::endpoint_id() const {
  return endpoint_id_;
}

void BarcodeScannerEndpoint::set_endpoint_id(std::string_view value_arg) {
  endpoint_id_ = value_arg;
}


const std::string& BarcodeScannerEndpoint::display_name() const {
  return display_name_;
}

void BarcodeScannerEndpoint::set_display_name(std::string_view value_arg) {
  display_name_ = value_arg;
}


const BarcodeScannerSource& BarcodeScannerEndpoint::source() const {
  return source_;
}

void BarcodeScannerEndpoint::set_source(const BarcodeScannerSource& value_arg) {
  source_ = value_arg;
}


const BarcodeScannerMode& BarcodeScannerEndpoint::mode() const {
  return mode_;
}

void BarcodeScannerEndpoint::set_mode(const BarcodeScannerMode& value_arg) {
  mode_ = value_arg;
}


const ScannerConnectionStatus& BarcodeScannerEndpoint::connection_status() const {
  return connection_status_;
}

void BarcodeScannerEndpoint::set_connection_status(const ScannerConnectionStatus& value_arg) {
  connection_status_ = value_arg;
}


bool BarcodeScannerEndpoint::active() const {
  return active_;
}

void BarcodeScannerEndpoint::set_active(bool value_arg) {
  active_ = value_arg;
}


bool BarcodeScannerEndpoint::preferred() const {
  return preferred_;
}

void BarcodeScannerEndpoint::set_preferred(bool value_arg) {
  preferred_ = value_arg;
}


const std::string* BarcodeScannerEndpoint::zebra_scanner_identifier() const {
  return zebra_scanner_identifier_ ? &(*zebra_scanner_identifier_) : nullptr;
}

void BarcodeScannerEndpoint::set_zebra_scanner_identifier(const std::string_view* value_arg) {
  zebra_scanner_identifier_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void BarcodeScannerEndpoint::set_zebra_scanner_identifier(std::string_view value_arg) {
  zebra_scanner_identifier_ = value_arg;
}


const int64_t* BarcodeScannerEndpoint::scanner_index() const {
  return scanner_index_ ? &(*scanner_index_) : nullptr;
}

void BarcodeScannerEndpoint::set_scanner_index(const int64_t* value_arg) {
  scanner_index_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void BarcodeScannerEndpoint::set_scanner_index(int64_t value_arg) {
  scanner_index_ = value_arg;
}


const int64_t* BarcodeScannerEndpoint::scanner_id() const {
  return scanner_id_ ? &(*scanner_id_) : nullptr;
}

void BarcodeScannerEndpoint::set_scanner_id(const int64_t* value_arg) {
  scanner_id_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void BarcodeScannerEndpoint::set_scanner_id(int64_t value_arg) {
  scanner_id_ = value_arg;
}


const std::string* BarcodeScannerEndpoint::model() const {
  return model_ ? &(*model_) : nullptr;
}

void BarcodeScannerEndpoint::set_model(const std::string_view* value_arg) {
  model_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void BarcodeScannerEndpoint::set_model(std::string_view value_arg) {
  model_ = value_arg;
}


const std::string* BarcodeScannerEndpoint::serial_number() const {
  return serial_number_ ? &(*serial_number_) : nullptr;
}

void BarcodeScannerEndpoint::set_serial_number(const std::string_view* value_arg) {
  serial_number_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void BarcodeScannerEndpoint::set_serial_number(std::string_view value_arg) {
  serial_number_ = value_arg;
}


EncodableList BarcodeScannerEndpoint::ToEncodableList() const {
  EncodableList list;
  list.reserve(12);
  list.push_back(EncodableValue(endpoint_id_));
  list.push_back(EncodableValue(display_name_));
  list.push_back(CustomEncodableValue(source_));
  list.push_back(CustomEncodableValue(mode_));
  list.push_back(CustomEncodableValue(connection_status_));
  list.push_back(EncodableValue(active_));
  list.push_back(EncodableValue(preferred_));
  list.push_back(zebra_scanner_identifier_ ? EncodableValue(*zebra_scanner_identifier_) : EncodableValue());
  list.push_back(scanner_index_ ? EncodableValue(*scanner_index_) : EncodableValue());
  list.push_back(scanner_id_ ? EncodableValue(*scanner_id_) : EncodableValue());
  list.push_back(model_ ? EncodableValue(*model_) : EncodableValue());
  list.push_back(serial_number_ ? EncodableValue(*serial_number_) : EncodableValue());
  return list;
}

BarcodeScannerEndpoint BarcodeScannerEndpoint::FromEncodableList(const EncodableList& list) {
  BarcodeScannerEndpoint decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::any_cast<const BarcodeScannerSource&>(std::get<CustomEncodableValue>(list[2])),
    std::any_cast<const BarcodeScannerMode&>(std::get<CustomEncodableValue>(list[3])),
    std::any_cast<const ScannerConnectionStatus&>(std::get<CustomEncodableValue>(list[4])),
    std::get<bool>(list[5]),
    std::get<bool>(list[6]));
  auto& encodable_zebra_scanner_identifier = list[7];
  if (!encodable_zebra_scanner_identifier.IsNull()) {
    decoded.set_zebra_scanner_identifier(std::get<std::string>(encodable_zebra_scanner_identifier));
  }
  auto& encodable_scanner_index = list[8];
  if (!encodable_scanner_index.IsNull()) {
    decoded.set_scanner_index(encodable_scanner_index.LongValue());
  }
  auto& encodable_scanner_id = list[9];
  if (!encodable_scanner_id.IsNull()) {
    decoded.set_scanner_id(encodable_scanner_id.LongValue());
  }
  auto& encodable_model = list[10];
  if (!encodable_model.IsNull()) {
    decoded.set_model(std::get<std::string>(encodable_model));
  }
  auto& encodable_serial_number = list[11];
  if (!encodable_serial_number.IsNull()) {
    decoded.set_serial_number(std::get<std::string>(encodable_serial_number));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ScannerConnectionType>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ScannerConnectionStatus>(enum_arg_value));
      }
    case 131: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<BarcodeScannerSource>(enum_arg_value));
      }
    case 132: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<BarcodeScannerMode>(enum_arg_value));
      }
    case 133: {
        return CustomEncodableValue(BarcodeScanner::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(Barcode::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 135: {
        return CustomEncodableValue(BarcodeScannerEndpoint::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(ScannerConnectionType)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ScannerConnectionType>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ScannerConnectionStatus)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ScannerConnectionStatus>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(BarcodeScannerSource)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<BarcodeScannerSource>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(BarcodeScannerMode)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<BarcodeScannerMode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(BarcodeScanner)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<BarcodeScanner>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(Barcode)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<Barcode>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(BarcodeScannerEndpoint)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<BarcodeScannerEndpoint>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by FlutterZebraBarcode.
const flutter::StandardMessageCodec& FlutterZebraBarcode::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `FlutterZebraBarcode` to handle messages through the `binary_messenger`.
void FlutterZebraBarcode::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  FlutterZebraBarcode* api) {
  FlutterZebraBarcode::SetUp(binary_messenger, api, "");
}

void FlutterZebraBarcode::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  FlutterZebraBarcode* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.updateAvailableScanners" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->UpdateAvailableScanners([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.connectScanner" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_scanner_id_arg = args.at(0);
          if (encodable_scanner_id_arg.IsNull()) {
            reply(WrapError("scanner_id_arg unexpectedly null."));
            return;
          }
          const int64_t scanner_id_arg = encodable_scanner_id_arg.LongValue();
          api->ConnectScanner(scanner_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.disconnectScanner" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->DisconnectScanner([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.refreshBarcodeScanners" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->RefreshBarcodeScanners([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.setActiveBarcodeScanner" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_endpoint_id_arg = args.at(0);
          if (encodable_endpoint_id_arg.IsNull()) {
            reply(WrapError("endpoint_id_arg unexpectedly null."));
            return;
          }
          const auto& endpoint_id_arg = std::get<std::string>(encodable_endpoint_id_arg);
          api->SetActiveBarcodeScanner(endpoint_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.clearActiveBarcodeScanner" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->ClearActiveBarcodeScanner([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.currentScanner" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<std::optional<BarcodeScanner>> output = api->CurrentScanner();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          auto output_optional = std::move(output).TakeValue();
          if (output_optional) {
            wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
          } else {
            wrapped.push_back(EncodableValue());
          }
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.activeBarcodeScanner" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<std::optional<BarcodeScannerEndpoint>> output = api->ActiveBarcodeScanner();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          auto output_optional = std::move(output).TakeValue();
          if (output_optional) {
            wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
          } else {
            wrapped.push_back(EncodableValue());
          }
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue FlutterZebraBarcode::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue FlutterZebraBarcode::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
FlutterZebraBarcodeCallbacks::FlutterZebraBarcodeCallbacks(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

FlutterZebraBarcodeCallbacks::FlutterZebraBarcodeCallbacks(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& FlutterZebraBarcodeCallbacks::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void FlutterZebraBarcodeCallbacks::OnAvailableScannersChanged(
  const EncodableList& readers_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onAvailableScannersChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(readers_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraBarcodeCallbacks::OnAvailableBarcodeScannersChanged(
  const EncodableList& endpoints_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onAvailableBarcodeScannersChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(endpoints_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraBarcodeCallbacks::OnActiveBarcodeScannerChanged(
  const BarcodeScannerEndpoint* endpoint_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onActiveBarcodeScannerChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    endpoint_arg ? CustomEncodableValue(*endpoint_arg) : EncodableValue(),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraBarcodeCallbacks::OnScannerConnectionStatusChanged(
  const ScannerConnectionStatus& status_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onScannerConnectionStatusChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(status_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraBarcodeCallbacks::OnBarcodeRead(
  const Barcode& barcode_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onBarcodeRead" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(barcode_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

}  // namespace flutter_zebra_barcode
