// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_FLUTTER_ZEBRA_RFID_G_H_
#define PIGEON_FLUTTER_ZEBRA_RFID_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>
#include <utility>
#include <variant>

namespace flutter_zebra_rfid {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class FlutterZebraRfid;
  friend class FlutterZebraRfidCallbacks;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class ReaderConnectionType {
  kBluetooth = 0,
  kUsb = 1,
  kAll = 2
};

enum class ReaderConnectionStatus {
  kConnecting = 0,
  kConnected = 1,
  kDisconnecting = 2,
  kDisconnected = 3,
  kError = 4
};

enum class BluetoothScanStatus {
  kScanning = 0,
  kFinished = 1,
  kError = 2
};

enum class ReaderErrorCode {
  kUnknown = 0,
  kNoAvailableReaders = 1,
  kInvalidReaderIndex = 2,
  kReaderDeviceNull = 3,
  kAlreadyConnecting = 4,
  kNotConnected = 5,
  kSdkInvalidUsage = 6,
  kSdkOperationFailure = 7,
  kTimeout = 8
};

enum class ReaderConfigBatchMode {
  kAuto = 0,
  kEnabled = 1,
  kDisabled = 2
};

enum class ReaderBeeperVolume {
  kQuiet = 0,
  kLow = 1,
  kMedium = 2,
  kHigh = 3
};


// Generated class from Pigeon that represents data sent in messages.
class ReaderError {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ReaderError(
    const ReaderErrorCode& code,
    const std::string& message);

  // Constructs an object setting all fields.
  explicit ReaderError(
    const ReaderErrorCode& code,
    const std::string& message,
    const std::string* details);

  const ReaderErrorCode& code() const;
  void set_code(const ReaderErrorCode& value_arg);

  const std::string& message() const;
  void set_message(std::string_view value_arg);

  const std::string* details() const;
  void set_details(const std::string_view* value_arg);
  void set_details(std::string_view value_arg);


 private:
  static ReaderError FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FlutterZebraRfid;
  friend class FlutterZebraRfidCallbacks;
  friend class PigeonInternalCodecSerializer;
  ReaderErrorCode code_;
  std::string message_;
  std::optional<std::string> details_;

};


// Generated class from Pigeon that represents data sent in messages.
class Reader {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit Reader(int64_t id);

  // Constructs an object setting all fields.
  explicit Reader(
    const std::string* name,
    int64_t id,
    const ReaderInfo* info);

  ~Reader() = default;
  Reader(const Reader& other);
  Reader& operator=(const Reader& other);
  Reader(Reader&& other) = default;
  Reader& operator=(Reader&& other) noexcept = default;
  const std::string* name() const;
  void set_name(const std::string_view* value_arg);
  void set_name(std::string_view value_arg);

  int64_t id() const;
  void set_id(int64_t value_arg);

  const ReaderInfo* info() const;
  void set_info(const ReaderInfo* value_arg);
  void set_info(const ReaderInfo& value_arg);


 private:
  static Reader FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FlutterZebraRfid;
  friend class FlutterZebraRfidCallbacks;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> name_;
  int64_t id_;
  std::unique_ptr<ReaderInfo> info_;

};


// Generated class from Pigeon that represents data sent in messages.
class BluetoothDevice {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit BluetoothDevice(
    const std::string& address,
    bool is_paired);

  // Constructs an object setting all fields.
  explicit BluetoothDevice(
    const std::string* name,
    const std::string& address,
    bool is_paired);

  const std::string* name() const;
  void set_name(const std::string_view* value_arg);
  void set_name(std::string_view value_arg);

  const std::string& address() const;
  void set_address(std::string_view value_arg);

  bool is_paired() const;
  void set_is_paired(bool value_arg);


 private:
  static BluetoothDevice FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FlutterZebraRfid;
  friend class FlutterZebraRfidCallbacks;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> name_;
  std::string address_;
  bool is_paired_;

};


// Generated class from Pigeon that represents data sent in messages.
class ReaderConfig {
 public:
  // Constructs an object setting all non-nullable fields.
  ReaderConfig();

  // Constructs an object setting all fields.
  explicit ReaderConfig(
    const int64_t* transmit_power_index,
    const int64_t* tari,
    const ReaderBeeperVolume* beeper_volume,
    const bool* enable_dynamic_power,
    const bool* enable_led_blink,
    const ReaderConfigBatchMode* batch_mode,
    const ReaderConfigBatchMode* scan_batch_mode,
    const int64_t* rf_mode_table_index,
    const int64_t* receive_sensitivity_index);

  const int64_t* transmit_power_index() const;
  void set_transmit_power_index(const int64_t* value_arg);
  void set_transmit_power_index(int64_t value_arg);

  const int64_t* tari() const;
  void set_tari(const int64_t* value_arg);
  void set_tari(int64_t value_arg);

  const ReaderBeeperVolume* beeper_volume() const;
  void set_beeper_volume(const ReaderBeeperVolume* value_arg);
  void set_beeper_volume(const ReaderBeeperVolume& value_arg);

  const bool* enable_dynamic_power() const;
  void set_enable_dynamic_power(const bool* value_arg);
  void set_enable_dynamic_power(bool value_arg);

  const bool* enable_led_blink() const;
  void set_enable_led_blink(const bool* value_arg);
  void set_enable_led_blink(bool value_arg);

  const ReaderConfigBatchMode* batch_mode() const;
  void set_batch_mode(const ReaderConfigBatchMode* value_arg);
  void set_batch_mode(const ReaderConfigBatchMode& value_arg);

  const ReaderConfigBatchMode* scan_batch_mode() const;
  void set_scan_batch_mode(const ReaderConfigBatchMode* value_arg);
  void set_scan_batch_mode(const ReaderConfigBatchMode& value_arg);

  const int64_t* rf_mode_table_index() const;
  void set_rf_mode_table_index(const int64_t* value_arg);
  void set_rf_mode_table_index(int64_t value_arg);

  const int64_t* receive_sensitivity_index() const;
  void set_receive_sensitivity_index(const int64_t* value_arg);
  void set_receive_sensitivity_index(int64_t value_arg);


 private:
  static ReaderConfig FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FlutterZebraRfid;
  friend class FlutterZebraRfidCallbacks;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> transmit_power_index_;
  std::optional<int64_t> tari_;
  std::optional<ReaderBeeperVolume> beeper_volume_;
  std::optional<bool> enable_dynamic_power_;
  std::optional<bool> enable_led_blink_;
  std::optional<ReaderConfigBatchMode> batch_mode_;
  std::optional<ReaderConfigBatchMode> scan_batch_mode_;
  std::optional<int64_t> rf_mode_table_index_;
  std::optional<int64_t> receive_sensitivity_index_;

};


// Generated class from Pigeon that represents data sent in messages.
class ReaderInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ReaderInfo(const flutter::EncodableList& transmit_power_levels);

  // Constructs an object setting all fields.
  explicit ReaderInfo(
    const flutter::EncodableList& transmit_power_levels,
    const std::string* firmware_version,
    const std::string* model_version,
    const std::string* scanner_name,
    const std::string* serial_number);

  const flutter::EncodableList& transmit_power_levels() const;
  void set_transmit_power_levels(const flutter::EncodableList& value_arg);

  const std::string* firmware_version() const;
  void set_firmware_version(const std::string_view* value_arg);
  void set_firmware_version(std::string_view value_arg);

  const std::string* model_version() const;
  void set_model_version(const std::string_view* value_arg);
  void set_model_version(std::string_view value_arg);

  const std::string* scanner_name() const;
  void set_scanner_name(const std::string_view* value_arg);
  void set_scanner_name(std::string_view value_arg);

  const std::string* serial_number() const;
  void set_serial_number(const std::string_view* value_arg);
  void set_serial_number(std::string_view value_arg);


 private:
  static ReaderInfo FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class Reader;
  friend class FlutterZebraRfid;
  friend class FlutterZebraRfidCallbacks;
  friend class PigeonInternalCodecSerializer;
  flutter::EncodableList transmit_power_levels_;
  std::optional<std::string> firmware_version_;
  std::optional<std::string> model_version_;
  std::optional<std::string> scanner_name_;
  std::optional<std::string> serial_number_;

};


// Generated class from Pigeon that represents data sent in messages.
class ReaderRegion {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ReaderRegion(const std::string& code);

  // Constructs an object setting all fields.
  explicit ReaderRegion(
    const std::string& code,
    const std::string* name,
    const std::string* standard_name);

  const std::string& code() const;
  void set_code(std::string_view value_arg);

  const std::string* name() const;
  void set_name(const std::string_view* value_arg);
  void set_name(std::string_view value_arg);

  const std::string* standard_name() const;
  void set_standard_name(const std::string_view* value_arg);
  void set_standard_name(std::string_view value_arg);


 private:
  static ReaderRegion FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FlutterZebraRfid;
  friend class FlutterZebraRfidCallbacks;
  friend class PigeonInternalCodecSerializer;
  std::string code_;
  std::optional<std::string> name_;
  std::optional<std::string> standard_name_;

};


// Generated class from Pigeon that represents data sent in messages.
class RfidTag {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit RfidTag(
    const std::string& id,
    int64_t rssi);

  // Constructs an object setting all fields.
  explicit RfidTag(
    const std::string& id,
    int64_t rssi,
    const double* relative_distance);

  const std::string& id() const;
  void set_id(std::string_view value_arg);

  int64_t rssi() const;
  void set_rssi(int64_t value_arg);

  const double* relative_distance() const;
  void set_relative_distance(const double* value_arg);
  void set_relative_distance(double value_arg);


 private:
  static RfidTag FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FlutterZebraRfid;
  friend class FlutterZebraRfidCallbacks;
  friend class PigeonInternalCodecSerializer;
  std::string id_;
  int64_t rssi_;
  std::optional<double> relative_distance_;

};


// Generated class from Pigeon that represents data sent in messages.
class BatteryData {
 public:
  // Constructs an object setting all fields.
  explicit BatteryData(
    int64_t level,
    bool is_charging,
    const std::string& cause);

  int64_t level() const;
  void set_level(int64_t value_arg);

  bool is_charging() const;
  void set_is_charging(bool value_arg);

  const std::string& cause() const;
  void set_cause(std::string_view value_arg);


 private:
  static BatteryData FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FlutterZebraRfid;
  friend class FlutterZebraRfidCallbacks;
  friend class PigeonInternalCodecSerializer;
  int64_t level_;
  bool is_charging_;
  std::string cause_;

};


// Generated class from Pigeon that represents data sent in messages.
class Diagnostics {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit Diagnostics(
    const ReaderConnectionStatus& connection_state,
    int64_t connect_attempts,
    bool is_locating);

  // Constructs an object setting all fields.
  explicit Diagnostics(
    const ReaderConnectionStatus& connection_state,
    int64_t connect_attempts,
    const ReaderErrorCode* last_error_code,
    const std::string* last_error_message,
    const int64_t* last_connect_start_ms,
    const int64_t* last_connect_duration_ms,
    bool is_locating,
    const bool* scanning_enabled,
    const int64_t* scanning_enabled_last_toggle_ms,
    const bool* inventory_active,
    const int64_t* last_inventory_start_ms,
    const int64_t* last_inventory_stop_ms,
    const bool* pending_purge_active,
    const std::string* last_inventory_stop_reason,
    const std::string* last_inventory_start_reason);

  const ReaderConnectionStatus& connection_state() const;
  void set_connection_state(const ReaderConnectionStatus& value_arg);

  int64_t connect_attempts() const;
  void set_connect_attempts(int64_t value_arg);

  const ReaderErrorCode* last_error_code() const;
  void set_last_error_code(const ReaderErrorCode* value_arg);
  void set_last_error_code(const ReaderErrorCode& value_arg);

  const std::string* last_error_message() const;
  void set_last_error_message(const std::string_view* value_arg);
  void set_last_error_message(std::string_view value_arg);

  const int64_t* last_connect_start_ms() const;
  void set_last_connect_start_ms(const int64_t* value_arg);
  void set_last_connect_start_ms(int64_t value_arg);

  const int64_t* last_connect_duration_ms() const;
  void set_last_connect_duration_ms(const int64_t* value_arg);
  void set_last_connect_duration_ms(int64_t value_arg);

  bool is_locating() const;
  void set_is_locating(bool value_arg);

  const bool* scanning_enabled() const;
  void set_scanning_enabled(const bool* value_arg);
  void set_scanning_enabled(bool value_arg);

  const int64_t* scanning_enabled_last_toggle_ms() const;
  void set_scanning_enabled_last_toggle_ms(const int64_t* value_arg);
  void set_scanning_enabled_last_toggle_ms(int64_t value_arg);

  const bool* inventory_active() const;
  void set_inventory_active(const bool* value_arg);
  void set_inventory_active(bool value_arg);

  const int64_t* last_inventory_start_ms() const;
  void set_last_inventory_start_ms(const int64_t* value_arg);
  void set_last_inventory_start_ms(int64_t value_arg);

  const int64_t* last_inventory_stop_ms() const;
  void set_last_inventory_stop_ms(const int64_t* value_arg);
  void set_last_inventory_stop_ms(int64_t value_arg);

  const bool* pending_purge_active() const;
  void set_pending_purge_active(const bool* value_arg);
  void set_pending_purge_active(bool value_arg);

  const std::string* last_inventory_stop_reason() const;
  void set_last_inventory_stop_reason(const std::string_view* value_arg);
  void set_last_inventory_stop_reason(std::string_view value_arg);

  const std::string* last_inventory_start_reason() const;
  void set_last_inventory_start_reason(const std::string_view* value_arg);
  void set_last_inventory_start_reason(std::string_view value_arg);


 private:
  static Diagnostics FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FlutterZebraRfid;
  friend class FlutterZebraRfidCallbacks;
  friend class PigeonInternalCodecSerializer;
  ReaderConnectionStatus connection_state_;
  int64_t connect_attempts_;
  std::optional<ReaderErrorCode> last_error_code_;
  std::optional<std::string> last_error_message_;
  std::optional<int64_t> last_connect_start_ms_;
  std::optional<int64_t> last_connect_duration_ms_;
  bool is_locating_;
  std::optional<bool> scanning_enabled_;
  std::optional<int64_t> scanning_enabled_last_toggle_ms_;
  std::optional<bool> inventory_active_;
  std::optional<int64_t> last_inventory_start_ms_;
  std::optional<int64_t> last_inventory_stop_ms_;
  std::optional<bool> pending_purge_active_;
  std::optional<std::string> last_inventory_stop_reason_;
  std::optional<std::string> last_inventory_start_reason_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class FlutterZebraRfid {
 public:
  FlutterZebraRfid(const FlutterZebraRfid&) = delete;
  FlutterZebraRfid& operator=(const FlutterZebraRfid&) = delete;
  virtual ~FlutterZebraRfid() {}
  // Returns list with names of available readers for specified `connectionType`.
  virtual void UpdateAvailableReaders(
    const ReaderConnectionType& connection_type,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Starts Bluetooth classic device discovery for pairing.
  virtual void StartBluetoothScan(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Stops Bluetooth classic device discovery.
  virtual void StopBluetoothScan(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Returns currently bonded Bluetooth devices.
  virtual void GetBondedDevices(std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // Starts pairing with the Bluetooth device at `address`.
  virtual void PairBluetoothDevice(
    const std::string& address,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Connects to a reader with `readerId` ID.
  virtual void ConnectReader(
    int64_t reader_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Configures reader with `config`.
  virtual void ConfigureReader(
    const ReaderConfig& config,
    bool should_persist,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Disconnects a current reader.
  virtual void DisconnectReader(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Trigger device status
  virtual void TriggerDeviceStatus(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Start locating the specified `tags`.
  // If `disableBeep` is true, the reader will not beep for tags not in the locate list.
  virtual void StartLocating(
    const flutter::EncodableList& tags,
    const bool* disable_beep,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Stop locating tags.
  virtual void StopLocating(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Reset the locate state (clears session, allows new locate operations).
  virtual void ResetLocateState(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Reader currently in use
  virtual ErrorOr<std::optional<Reader>> CurrentReader() = 0;
  // Reader config
  virtual void ReaderConfig(std::function<void(ErrorOr<ReaderConfig> reply)> result) = 0;
  // Supported regulatory regions for the current or last-selected reader.
  virtual void SupportedReaderRegions(std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // Applies a regulatory region to the current reader.
  virtual void SetReaderRegion(
    const std::string& region_code,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Runtime diagnostics snapshot (counters / last error / state)
  virtual void Diagnostics(std::function<void(ErrorOr<Diagnostics> reply)> result) = 0;
  // Enable or disable hardware-trigger initiated scanning/inventory.
  // When disabled, trigger pulls are ignored and any active inventory is stopped.
  virtual void SetScanningEnabled(
    bool enabled,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by FlutterZebraRfid.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `FlutterZebraRfid` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    FlutterZebraRfid* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    FlutterZebraRfid* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  FlutterZebraRfid() = default;

};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class FlutterZebraRfidCallbacks {
 public:
  FlutterZebraRfidCallbacks(flutter::BinaryMessenger* binary_messenger);
  FlutterZebraRfidCallbacks(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnAvailableReadersChanged(
    const flutter::EncodableList& readers,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnReaderConnectionStatusChanged(
    const ReaderConnectionStatus& status,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnTagsRead(
    const flutter::EncodableList& tags,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnBatteryDataReceived(
    const BatteryData& battery_data,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnTagsLocated(
    const flutter::EncodableList& tags,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnBluetoothDeviceDiscovered(
    const BluetoothDevice& device,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnBluetoothScanStatusChanged(
    const BluetoothScanStatus& status,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnBluetoothPairingResult(
    const BluetoothDevice& device,
    bool success,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnReaderConnectionError(
    const ReaderError& error,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace flutter_zebra_rfid
#endif  // PIGEON_FLUTTER_ZEBRA_RFID_G_H_
