// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "flutter_zebra_rfid.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace flutter_zebra_rfid {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// ReaderError

ReaderError::ReaderError(
  const ReaderErrorCode& code,
  const std::string& message)
 : code_(code),
    message_(message) {}

ReaderError::ReaderError(
  const ReaderErrorCode& code,
  const std::string& message,
  const std::string* details)
 : code_(code),
    message_(message),
    details_(details ? std::optional<std::string>(*details) : std::nullopt) {}

const ReaderErrorCode& ReaderError::code() const {
  return code_;
}

void ReaderError::set_code(const ReaderErrorCode& value_arg) {
  code_ = value_arg;
}


const std::string& ReaderError::message() const {
  return message_;
}

void ReaderError::set_message(std::string_view value_arg) {
  message_ = value_arg;
}


const std::string* ReaderError::details() const {
  return details_ ? &(*details_) : nullptr;
}

void ReaderError::set_details(const std::string_view* value_arg) {
  details_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ReaderError::set_details(std::string_view value_arg) {
  details_ = value_arg;
}


EncodableList ReaderError::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(CustomEncodableValue(code_));
  list.push_back(EncodableValue(message_));
  list.push_back(details_ ? EncodableValue(*details_) : EncodableValue());
  return list;
}

ReaderError ReaderError::FromEncodableList(const EncodableList& list) {
  ReaderError decoded(
    std::any_cast<const ReaderErrorCode&>(std::get<CustomEncodableValue>(list[0])),
    std::get<std::string>(list[1]));
  auto& encodable_details = list[2];
  if (!encodable_details.IsNull()) {
    decoded.set_details(std::get<std::string>(encodable_details));
  }
  return decoded;
}

// Reader

Reader::Reader(int64_t id)
 : id_(id) {}

Reader::Reader(
  const std::string* name,
  int64_t id,
  const ReaderInfo* info)
 : name_(name ? std::optional<std::string>(*name) : std::nullopt),
    id_(id),
    info_(info ? std::make_unique<ReaderInfo>(*info) : nullptr) {}

Reader::Reader(const Reader& other)
 : name_(other.name_ ? std::optional<std::string>(*other.name_) : std::nullopt),
    id_(other.id_),
    info_(other.info_ ? std::make_unique<ReaderInfo>(*other.info_) : nullptr) {}

Reader& Reader::operator=(const Reader& other) {
  name_ = other.name_;
  id_ = other.id_;
  info_ = other.info_ ? std::make_unique<ReaderInfo>(*other.info_) : nullptr;
  return *this;
}

const std::string* Reader::name() const {
  return name_ ? &(*name_) : nullptr;
}

void Reader::set_name(const std::string_view* value_arg) {
  name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void Reader::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


int64_t Reader::id() const {
  return id_;
}

void Reader::set_id(int64_t value_arg) {
  id_ = value_arg;
}


const ReaderInfo* Reader::info() const {
  return info_.get();
}

void Reader::set_info(const ReaderInfo* value_arg) {
  info_ = value_arg ? std::make_unique<ReaderInfo>(*value_arg) : nullptr;
}

void Reader::set_info(const ReaderInfo& value_arg) {
  info_ = std::make_unique<ReaderInfo>(value_arg);
}


EncodableList Reader::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(name_ ? EncodableValue(*name_) : EncodableValue());
  list.push_back(EncodableValue(id_));
  list.push_back(info_ ? CustomEncodableValue(*info_) : EncodableValue());
  return list;
}

Reader Reader::FromEncodableList(const EncodableList& list) {
  Reader decoded(
    list[1].LongValue());
  auto& encodable_name = list[0];
  if (!encodable_name.IsNull()) {
    decoded.set_name(std::get<std::string>(encodable_name));
  }
  auto& encodable_info = list[2];
  if (!encodable_info.IsNull()) {
    decoded.set_info(std::any_cast<const ReaderInfo&>(std::get<CustomEncodableValue>(encodable_info)));
  }
  return decoded;
}

// BluetoothDevice

BluetoothDevice::BluetoothDevice(
  const std::string& address,
  bool is_paired)
 : address_(address),
    is_paired_(is_paired) {}

BluetoothDevice::BluetoothDevice(
  const std::string* name,
  const std::string& address,
  bool is_paired)
 : name_(name ? std::optional<std::string>(*name) : std::nullopt),
    address_(address),
    is_paired_(is_paired) {}

const std::string* BluetoothDevice::name() const {
  return name_ ? &(*name_) : nullptr;
}

void BluetoothDevice::set_name(const std::string_view* value_arg) {
  name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void BluetoothDevice::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::string& BluetoothDevice::address() const {
  return address_;
}

void BluetoothDevice::set_address(std::string_view value_arg) {
  address_ = value_arg;
}


bool BluetoothDevice::is_paired() const {
  return is_paired_;
}

void BluetoothDevice::set_is_paired(bool value_arg) {
  is_paired_ = value_arg;
}


EncodableList BluetoothDevice::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(name_ ? EncodableValue(*name_) : EncodableValue());
  list.push_back(EncodableValue(address_));
  list.push_back(EncodableValue(is_paired_));
  return list;
}

BluetoothDevice BluetoothDevice::FromEncodableList(const EncodableList& list) {
  BluetoothDevice decoded(
    std::get<std::string>(list[1]),
    std::get<bool>(list[2]));
  auto& encodable_name = list[0];
  if (!encodable_name.IsNull()) {
    decoded.set_name(std::get<std::string>(encodable_name));
  }
  return decoded;
}

// ReaderConfig

ReaderConfig::ReaderConfig() {}

ReaderConfig::ReaderConfig(
  const int64_t* transmit_power_index,
  const int64_t* tari,
  const ReaderBeeperVolume* beeper_volume,
  const bool* enable_dynamic_power,
  const bool* enable_led_blink,
  const ReaderConfigBatchMode* batch_mode,
  const ReaderConfigBatchMode* scan_batch_mode,
  const int64_t* rf_mode_table_index,
  const int64_t* receive_sensitivity_index)
 : transmit_power_index_(transmit_power_index ? std::optional<int64_t>(*transmit_power_index) : std::nullopt),
    tari_(tari ? std::optional<int64_t>(*tari) : std::nullopt),
    beeper_volume_(beeper_volume ? std::optional<ReaderBeeperVolume>(*beeper_volume) : std::nullopt),
    enable_dynamic_power_(enable_dynamic_power ? std::optional<bool>(*enable_dynamic_power) : std::nullopt),
    enable_led_blink_(enable_led_blink ? std::optional<bool>(*enable_led_blink) : std::nullopt),
    batch_mode_(batch_mode ? std::optional<ReaderConfigBatchMode>(*batch_mode) : std::nullopt),
    scan_batch_mode_(scan_batch_mode ? std::optional<ReaderConfigBatchMode>(*scan_batch_mode) : std::nullopt),
    rf_mode_table_index_(rf_mode_table_index ? std::optional<int64_t>(*rf_mode_table_index) : std::nullopt),
    receive_sensitivity_index_(receive_sensitivity_index ? std::optional<int64_t>(*receive_sensitivity_index) : std::nullopt) {}

const int64_t* ReaderConfig::transmit_power_index() const {
  return transmit_power_index_ ? &(*transmit_power_index_) : nullptr;
}

void ReaderConfig::set_transmit_power_index(const int64_t* value_arg) {
  transmit_power_index_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ReaderConfig::set_transmit_power_index(int64_t value_arg) {
  transmit_power_index_ = value_arg;
}


const int64_t* ReaderConfig::tari() const {
  return tari_ ? &(*tari_) : nullptr;
}

void ReaderConfig::set_tari(const int64_t* value_arg) {
  tari_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ReaderConfig::set_tari(int64_t value_arg) {
  tari_ = value_arg;
}


const ReaderBeeperVolume* ReaderConfig::beeper_volume() const {
  return beeper_volume_ ? &(*beeper_volume_) : nullptr;
}

void ReaderConfig::set_beeper_volume(const ReaderBeeperVolume* value_arg) {
  beeper_volume_ = value_arg ? std::optional<ReaderBeeperVolume>(*value_arg) : std::nullopt;
}

void ReaderConfig::set_beeper_volume(const ReaderBeeperVolume& value_arg) {
  beeper_volume_ = value_arg;
}


const bool* ReaderConfig::enable_dynamic_power() const {
  return enable_dynamic_power_ ? &(*enable_dynamic_power_) : nullptr;
}

void ReaderConfig::set_enable_dynamic_power(const bool* value_arg) {
  enable_dynamic_power_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void ReaderConfig::set_enable_dynamic_power(bool value_arg) {
  enable_dynamic_power_ = value_arg;
}


const bool* ReaderConfig::enable_led_blink() const {
  return enable_led_blink_ ? &(*enable_led_blink_) : nullptr;
}

void ReaderConfig::set_enable_led_blink(const bool* value_arg) {
  enable_led_blink_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void ReaderConfig::set_enable_led_blink(bool value_arg) {
  enable_led_blink_ = value_arg;
}


const ReaderConfigBatchMode* ReaderConfig::batch_mode() const {
  return batch_mode_ ? &(*batch_mode_) : nullptr;
}

void ReaderConfig::set_batch_mode(const ReaderConfigBatchMode* value_arg) {
  batch_mode_ = value_arg ? std::optional<ReaderConfigBatchMode>(*value_arg) : std::nullopt;
}

void ReaderConfig::set_batch_mode(const ReaderConfigBatchMode& value_arg) {
  batch_mode_ = value_arg;
}


const ReaderConfigBatchMode* ReaderConfig::scan_batch_mode() const {
  return scan_batch_mode_ ? &(*scan_batch_mode_) : nullptr;
}

void ReaderConfig::set_scan_batch_mode(const ReaderConfigBatchMode* value_arg) {
  scan_batch_mode_ = value_arg ? std::optional<ReaderConfigBatchMode>(*value_arg) : std::nullopt;
}

void ReaderConfig::set_scan_batch_mode(const ReaderConfigBatchMode& value_arg) {
  scan_batch_mode_ = value_arg;
}


const int64_t* ReaderConfig::rf_mode_table_index() const {
  return rf_mode_table_index_ ? &(*rf_mode_table_index_) : nullptr;
}

void ReaderConfig::set_rf_mode_table_index(const int64_t* value_arg) {
  rf_mode_table_index_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ReaderConfig::set_rf_mode_table_index(int64_t value_arg) {
  rf_mode_table_index_ = value_arg;
}


const int64_t* ReaderConfig::receive_sensitivity_index() const {
  return receive_sensitivity_index_ ? &(*receive_sensitivity_index_) : nullptr;
}

void ReaderConfig::set_receive_sensitivity_index(const int64_t* value_arg) {
  receive_sensitivity_index_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ReaderConfig::set_receive_sensitivity_index(int64_t value_arg) {
  receive_sensitivity_index_ = value_arg;
}


EncodableList ReaderConfig::ToEncodableList() const {
  EncodableList list;
  list.reserve(9);
  list.push_back(transmit_power_index_ ? EncodableValue(*transmit_power_index_) : EncodableValue());
  list.push_back(tari_ ? EncodableValue(*tari_) : EncodableValue());
  list.push_back(beeper_volume_ ? CustomEncodableValue(*beeper_volume_) : EncodableValue());
  list.push_back(enable_dynamic_power_ ? EncodableValue(*enable_dynamic_power_) : EncodableValue());
  list.push_back(enable_led_blink_ ? EncodableValue(*enable_led_blink_) : EncodableValue());
  list.push_back(batch_mode_ ? CustomEncodableValue(*batch_mode_) : EncodableValue());
  list.push_back(scan_batch_mode_ ? CustomEncodableValue(*scan_batch_mode_) : EncodableValue());
  list.push_back(rf_mode_table_index_ ? EncodableValue(*rf_mode_table_index_) : EncodableValue());
  list.push_back(receive_sensitivity_index_ ? EncodableValue(*receive_sensitivity_index_) : EncodableValue());
  return list;
}

ReaderConfig ReaderConfig::FromEncodableList(const EncodableList& list) {
  ReaderConfig decoded;
  auto& encodable_transmit_power_index = list[0];
  if (!encodable_transmit_power_index.IsNull()) {
    decoded.set_transmit_power_index(encodable_transmit_power_index.LongValue());
  }
  auto& encodable_tari = list[1];
  if (!encodable_tari.IsNull()) {
    decoded.set_tari(encodable_tari.LongValue());
  }
  auto& encodable_beeper_volume = list[2];
  if (!encodable_beeper_volume.IsNull()) {
    decoded.set_beeper_volume(std::any_cast<const ReaderBeeperVolume&>(std::get<CustomEncodableValue>(encodable_beeper_volume)));
  }
  auto& encodable_enable_dynamic_power = list[3];
  if (!encodable_enable_dynamic_power.IsNull()) {
    decoded.set_enable_dynamic_power(std::get<bool>(encodable_enable_dynamic_power));
  }
  auto& encodable_enable_led_blink = list[4];
  if (!encodable_enable_led_blink.IsNull()) {
    decoded.set_enable_led_blink(std::get<bool>(encodable_enable_led_blink));
  }
  auto& encodable_batch_mode = list[5];
  if (!encodable_batch_mode.IsNull()) {
    decoded.set_batch_mode(std::any_cast<const ReaderConfigBatchMode&>(std::get<CustomEncodableValue>(encodable_batch_mode)));
  }
  auto& encodable_scan_batch_mode = list[6];
  if (!encodable_scan_batch_mode.IsNull()) {
    decoded.set_scan_batch_mode(std::any_cast<const ReaderConfigBatchMode&>(std::get<CustomEncodableValue>(encodable_scan_batch_mode)));
  }
  auto& encodable_rf_mode_table_index = list[7];
  if (!encodable_rf_mode_table_index.IsNull()) {
    decoded.set_rf_mode_table_index(encodable_rf_mode_table_index.LongValue());
  }
  auto& encodable_receive_sensitivity_index = list[8];
  if (!encodable_receive_sensitivity_index.IsNull()) {
    decoded.set_receive_sensitivity_index(encodable_receive_sensitivity_index.LongValue());
  }
  return decoded;
}

// ReaderInfo

ReaderInfo::ReaderInfo(const EncodableList& transmit_power_levels)
 : transmit_power_levels_(transmit_power_levels) {}

ReaderInfo::ReaderInfo(
  const EncodableList& transmit_power_levels,
  const std::string* firmware_version,
  const std::string* model_version,
  const std::string* scanner_name,
  const std::string* serial_number)
 : transmit_power_levels_(transmit_power_levels),
    firmware_version_(firmware_version ? std::optional<std::string>(*firmware_version) : std::nullopt),
    model_version_(model_version ? std::optional<std::string>(*model_version) : std::nullopt),
    scanner_name_(scanner_name ? std::optional<std::string>(*scanner_name) : std::nullopt),
    serial_number_(serial_number ? std::optional<std::string>(*serial_number) : std::nullopt) {}

const EncodableList& ReaderInfo::transmit_power_levels() const {
  return transmit_power_levels_;
}

void ReaderInfo::set_transmit_power_levels(const EncodableList& value_arg) {
  transmit_power_levels_ = value_arg;
}


const std::string* ReaderInfo::firmware_version() const {
  return firmware_version_ ? &(*firmware_version_) : nullptr;
}

void ReaderInfo::set_firmware_version(const std::string_view* value_arg) {
  firmware_version_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ReaderInfo::set_firmware_version(std::string_view value_arg) {
  firmware_version_ = value_arg;
}


const std::string* ReaderInfo::model_version() const {
  return model_version_ ? &(*model_version_) : nullptr;
}

void ReaderInfo::set_model_version(const std::string_view* value_arg) {
  model_version_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ReaderInfo::set_model_version(std::string_view value_arg) {
  model_version_ = value_arg;
}


const std::string* ReaderInfo::scanner_name() const {
  return scanner_name_ ? &(*scanner_name_) : nullptr;
}

void ReaderInfo::set_scanner_name(const std::string_view* value_arg) {
  scanner_name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ReaderInfo::set_scanner_name(std::string_view value_arg) {
  scanner_name_ = value_arg;
}


const std::string* ReaderInfo::serial_number() const {
  return serial_number_ ? &(*serial_number_) : nullptr;
}

void ReaderInfo::set_serial_number(const std::string_view* value_arg) {
  serial_number_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ReaderInfo::set_serial_number(std::string_view value_arg) {
  serial_number_ = value_arg;
}


EncodableList ReaderInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(EncodableValue(transmit_power_levels_));
  list.push_back(firmware_version_ ? EncodableValue(*firmware_version_) : EncodableValue());
  list.push_back(model_version_ ? EncodableValue(*model_version_) : EncodableValue());
  list.push_back(scanner_name_ ? EncodableValue(*scanner_name_) : EncodableValue());
  list.push_back(serial_number_ ? EncodableValue(*serial_number_) : EncodableValue());
  return list;
}

ReaderInfo ReaderInfo::FromEncodableList(const EncodableList& list) {
  ReaderInfo decoded(
    std::get<EncodableList>(list[0]));
  auto& encodable_firmware_version = list[1];
  if (!encodable_firmware_version.IsNull()) {
    decoded.set_firmware_version(std::get<std::string>(encodable_firmware_version));
  }
  auto& encodable_model_version = list[2];
  if (!encodable_model_version.IsNull()) {
    decoded.set_model_version(std::get<std::string>(encodable_model_version));
  }
  auto& encodable_scanner_name = list[3];
  if (!encodable_scanner_name.IsNull()) {
    decoded.set_scanner_name(std::get<std::string>(encodable_scanner_name));
  }
  auto& encodable_serial_number = list[4];
  if (!encodable_serial_number.IsNull()) {
    decoded.set_serial_number(std::get<std::string>(encodable_serial_number));
  }
  return decoded;
}

// ReaderRegion

ReaderRegion::ReaderRegion(const std::string& code)
 : code_(code) {}

ReaderRegion::ReaderRegion(
  const std::string& code,
  const std::string* name,
  const std::string* standard_name)
 : code_(code),
    name_(name ? std::optional<std::string>(*name) : std::nullopt),
    standard_name_(standard_name ? std::optional<std::string>(*standard_name) : std::nullopt) {}

const std::string& ReaderRegion::code() const {
  return code_;
}

void ReaderRegion::set_code(std::string_view value_arg) {
  code_ = value_arg;
}


const std::string* ReaderRegion::name() const {
  return name_ ? &(*name_) : nullptr;
}

void ReaderRegion::set_name(const std::string_view* value_arg) {
  name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ReaderRegion::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::string* ReaderRegion::standard_name() const {
  return standard_name_ ? &(*standard_name_) : nullptr;
}

void ReaderRegion::set_standard_name(const std::string_view* value_arg) {
  standard_name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ReaderRegion::set_standard_name(std::string_view value_arg) {
  standard_name_ = value_arg;
}


EncodableList ReaderRegion::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(code_));
  list.push_back(name_ ? EncodableValue(*name_) : EncodableValue());
  list.push_back(standard_name_ ? EncodableValue(*standard_name_) : EncodableValue());
  return list;
}

ReaderRegion ReaderRegion::FromEncodableList(const EncodableList& list) {
  ReaderRegion decoded(
    std::get<std::string>(list[0]));
  auto& encodable_name = list[1];
  if (!encodable_name.IsNull()) {
    decoded.set_name(std::get<std::string>(encodable_name));
  }
  auto& encodable_standard_name = list[2];
  if (!encodable_standard_name.IsNull()) {
    decoded.set_standard_name(std::get<std::string>(encodable_standard_name));
  }
  return decoded;
}

// RfidTag

RfidTag::RfidTag(
  const std::string& id,
  int64_t rssi)
 : id_(id),
    rssi_(rssi) {}

RfidTag::RfidTag(
  const std::string& id,
  int64_t rssi,
  const double* relative_distance)
 : id_(id),
    rssi_(rssi),
    relative_distance_(relative_distance ? std::optional<double>(*relative_distance) : std::nullopt) {}

const std::string& RfidTag::id() const {
  return id_;
}

void RfidTag::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


int64_t RfidTag::rssi() const {
  return rssi_;
}

void RfidTag::set_rssi(int64_t value_arg) {
  rssi_ = value_arg;
}


const double* RfidTag::relative_distance() const {
  return relative_distance_ ? &(*relative_distance_) : nullptr;
}

void RfidTag::set_relative_distance(const double* value_arg) {
  relative_distance_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void RfidTag::set_relative_distance(double value_arg) {
  relative_distance_ = value_arg;
}


EncodableList RfidTag::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(id_));
  list.push_back(EncodableValue(rssi_));
  list.push_back(relative_distance_ ? EncodableValue(*relative_distance_) : EncodableValue());
  return list;
}

RfidTag RfidTag::FromEncodableList(const EncodableList& list) {
  RfidTag decoded(
    std::get<std::string>(list[0]),
    list[1].LongValue());
  auto& encodable_relative_distance = list[2];
  if (!encodable_relative_distance.IsNull()) {
    decoded.set_relative_distance(std::get<double>(encodable_relative_distance));
  }
  return decoded;
}

// BatteryData

BatteryData::BatteryData(
  int64_t level,
  bool is_charging,
  const std::string& cause)
 : level_(level),
    is_charging_(is_charging),
    cause_(cause) {}

int64_t BatteryData::level() const {
  return level_;
}

void BatteryData::set_level(int64_t value_arg) {
  level_ = value_arg;
}


bool BatteryData::is_charging() const {
  return is_charging_;
}

void BatteryData::set_is_charging(bool value_arg) {
  is_charging_ = value_arg;
}


const std::string& BatteryData::cause() const {
  return cause_;
}

void BatteryData::set_cause(std::string_view value_arg) {
  cause_ = value_arg;
}


EncodableList BatteryData::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(level_));
  list.push_back(EncodableValue(is_charging_));
  list.push_back(EncodableValue(cause_));
  return list;
}

BatteryData BatteryData::FromEncodableList(const EncodableList& list) {
  BatteryData decoded(
    list[0].LongValue(),
    std::get<bool>(list[1]),
    std::get<std::string>(list[2]));
  return decoded;
}

// Diagnostics

Diagnostics::Diagnostics(
  const ReaderConnectionStatus& connection_state,
  int64_t connect_attempts,
  bool is_locating)
 : connection_state_(connection_state),
    connect_attempts_(connect_attempts),
    is_locating_(is_locating) {}

Diagnostics::Diagnostics(
  const ReaderConnectionStatus& connection_state,
  int64_t connect_attempts,
  const ReaderErrorCode* last_error_code,
  const std::string* last_error_message,
  const int64_t* last_connect_start_ms,
  const int64_t* last_connect_duration_ms,
  bool is_locating,
  const bool* scanning_enabled,
  const int64_t* scanning_enabled_last_toggle_ms,
  const bool* inventory_active,
  const int64_t* last_inventory_start_ms,
  const int64_t* last_inventory_stop_ms,
  const bool* pending_purge_active,
  const std::string* last_inventory_stop_reason,
  const std::string* last_inventory_start_reason)
 : connection_state_(connection_state),
    connect_attempts_(connect_attempts),
    last_error_code_(last_error_code ? std::optional<ReaderErrorCode>(*last_error_code) : std::nullopt),
    last_error_message_(last_error_message ? std::optional<std::string>(*last_error_message) : std::nullopt),
    last_connect_start_ms_(last_connect_start_ms ? std::optional<int64_t>(*last_connect_start_ms) : std::nullopt),
    last_connect_duration_ms_(last_connect_duration_ms ? std::optional<int64_t>(*last_connect_duration_ms) : std::nullopt),
    is_locating_(is_locating),
    scanning_enabled_(scanning_enabled ? std::optional<bool>(*scanning_enabled) : std::nullopt),
    scanning_enabled_last_toggle_ms_(scanning_enabled_last_toggle_ms ? std::optional<int64_t>(*scanning_enabled_last_toggle_ms) : std::nullopt),
    inventory_active_(inventory_active ? std::optional<bool>(*inventory_active) : std::nullopt),
    last_inventory_start_ms_(last_inventory_start_ms ? std::optional<int64_t>(*last_inventory_start_ms) : std::nullopt),
    last_inventory_stop_ms_(last_inventory_stop_ms ? std::optional<int64_t>(*last_inventory_stop_ms) : std::nullopt),
    pending_purge_active_(pending_purge_active ? std::optional<bool>(*pending_purge_active) : std::nullopt),
    last_inventory_stop_reason_(last_inventory_stop_reason ? std::optional<std::string>(*last_inventory_stop_reason) : std::nullopt),
    last_inventory_start_reason_(last_inventory_start_reason ? std::optional<std::string>(*last_inventory_start_reason) : std::nullopt) {}

const ReaderConnectionStatus& Diagnostics::connection_state() const {
  return connection_state_;
}

void Diagnostics::set_connection_state(const ReaderConnectionStatus& value_arg) {
  connection_state_ = value_arg;
}


int64_t Diagnostics::connect_attempts() const {
  return connect_attempts_;
}

void Diagnostics::set_connect_attempts(int64_t value_arg) {
  connect_attempts_ = value_arg;
}


const ReaderErrorCode* Diagnostics::last_error_code() const {
  return last_error_code_ ? &(*last_error_code_) : nullptr;
}

void Diagnostics::set_last_error_code(const ReaderErrorCode* value_arg) {
  last_error_code_ = value_arg ? std::optional<ReaderErrorCode>(*value_arg) : std::nullopt;
}

void Diagnostics::set_last_error_code(const ReaderErrorCode& value_arg) {
  last_error_code_ = value_arg;
}


const std::string* Diagnostics::last_error_message() const {
  return last_error_message_ ? &(*last_error_message_) : nullptr;
}

void Diagnostics::set_last_error_message(const std::string_view* value_arg) {
  last_error_message_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void Diagnostics::set_last_error_message(std::string_view value_arg) {
  last_error_message_ = value_arg;
}


const int64_t* Diagnostics::last_connect_start_ms() const {
  return last_connect_start_ms_ ? &(*last_connect_start_ms_) : nullptr;
}

void Diagnostics::set_last_connect_start_ms(const int64_t* value_arg) {
  last_connect_start_ms_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void Diagnostics::set_last_connect_start_ms(int64_t value_arg) {
  last_connect_start_ms_ = value_arg;
}


const int64_t* Diagnostics::last_connect_duration_ms() const {
  return last_connect_duration_ms_ ? &(*last_connect_duration_ms_) : nullptr;
}

void Diagnostics::set_last_connect_duration_ms(const int64_t* value_arg) {
  last_connect_duration_ms_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void Diagnostics::set_last_connect_duration_ms(int64_t value_arg) {
  last_connect_duration_ms_ = value_arg;
}


bool Diagnostics::is_locating() const {
  return is_locating_;
}

void Diagnostics::set_is_locating(bool value_arg) {
  is_locating_ = value_arg;
}


const bool* Diagnostics::scanning_enabled() const {
  return scanning_enabled_ ? &(*scanning_enabled_) : nullptr;
}

void Diagnostics::set_scanning_enabled(const bool* value_arg) {
  scanning_enabled_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void Diagnostics::set_scanning_enabled(bool value_arg) {
  scanning_enabled_ = value_arg;
}


const int64_t* Diagnostics::scanning_enabled_last_toggle_ms() const {
  return scanning_enabled_last_toggle_ms_ ? &(*scanning_enabled_last_toggle_ms_) : nullptr;
}

void Diagnostics::set_scanning_enabled_last_toggle_ms(const int64_t* value_arg) {
  scanning_enabled_last_toggle_ms_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void Diagnostics::set_scanning_enabled_last_toggle_ms(int64_t value_arg) {
  scanning_enabled_last_toggle_ms_ = value_arg;
}


const bool* Diagnostics::inventory_active() const {
  return inventory_active_ ? &(*inventory_active_) : nullptr;
}

void Diagnostics::set_inventory_active(const bool* value_arg) {
  inventory_active_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void Diagnostics::set_inventory_active(bool value_arg) {
  inventory_active_ = value_arg;
}


const int64_t* Diagnostics::last_inventory_start_ms() const {
  return last_inventory_start_ms_ ? &(*last_inventory_start_ms_) : nullptr;
}

void Diagnostics::set_last_inventory_start_ms(const int64_t* value_arg) {
  last_inventory_start_ms_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void Diagnostics::set_last_inventory_start_ms(int64_t value_arg) {
  last_inventory_start_ms_ = value_arg;
}


const int64_t* Diagnostics::last_inventory_stop_ms() const {
  return last_inventory_stop_ms_ ? &(*last_inventory_stop_ms_) : nullptr;
}

void Diagnostics::set_last_inventory_stop_ms(const int64_t* value_arg) {
  last_inventory_stop_ms_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void Diagnostics::set_last_inventory_stop_ms(int64_t value_arg) {
  last_inventory_stop_ms_ = value_arg;
}


const bool* Diagnostics::pending_purge_active() const {
  return pending_purge_active_ ? &(*pending_purge_active_) : nullptr;
}

void Diagnostics::set_pending_purge_active(const bool* value_arg) {
  pending_purge_active_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void Diagnostics::set_pending_purge_active(bool value_arg) {
  pending_purge_active_ = value_arg;
}


const std::string* Diagnostics::last_inventory_stop_reason() const {
  return last_inventory_stop_reason_ ? &(*last_inventory_stop_reason_) : nullptr;
}

void Diagnostics::set_last_inventory_stop_reason(const std::string_view* value_arg) {
  last_inventory_stop_reason_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void Diagnostics::set_last_inventory_stop_reason(std::string_view value_arg) {
  last_inventory_stop_reason_ = value_arg;
}


const std::string* Diagnostics::last_inventory_start_reason() const {
  return last_inventory_start_reason_ ? &(*last_inventory_start_reason_) : nullptr;
}

void Diagnostics::set_last_inventory_start_reason(const std::string_view* value_arg) {
  last_inventory_start_reason_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void Diagnostics::set_last_inventory_start_reason(std::string_view value_arg) {
  last_inventory_start_reason_ = value_arg;
}


EncodableList Diagnostics::ToEncodableList() const {
  EncodableList list;
  list.reserve(15);
  list.push_back(CustomEncodableValue(connection_state_));
  list.push_back(EncodableValue(connect_attempts_));
  list.push_back(last_error_code_ ? CustomEncodableValue(*last_error_code_) : EncodableValue());
  list.push_back(last_error_message_ ? EncodableValue(*last_error_message_) : EncodableValue());
  list.push_back(last_connect_start_ms_ ? EncodableValue(*last_connect_start_ms_) : EncodableValue());
  list.push_back(last_connect_duration_ms_ ? EncodableValue(*last_connect_duration_ms_) : EncodableValue());
  list.push_back(EncodableValue(is_locating_));
  list.push_back(scanning_enabled_ ? EncodableValue(*scanning_enabled_) : EncodableValue());
  list.push_back(scanning_enabled_last_toggle_ms_ ? EncodableValue(*scanning_enabled_last_toggle_ms_) : EncodableValue());
  list.push_back(inventory_active_ ? EncodableValue(*inventory_active_) : EncodableValue());
  list.push_back(last_inventory_start_ms_ ? EncodableValue(*last_inventory_start_ms_) : EncodableValue());
  list.push_back(last_inventory_stop_ms_ ? EncodableValue(*last_inventory_stop_ms_) : EncodableValue());
  list.push_back(pending_purge_active_ ? EncodableValue(*pending_purge_active_) : EncodableValue());
  list.push_back(last_inventory_stop_reason_ ? EncodableValue(*last_inventory_stop_reason_) : EncodableValue());
  list.push_back(last_inventory_start_reason_ ? EncodableValue(*last_inventory_start_reason_) : EncodableValue());
  return list;
}

Diagnostics Diagnostics::FromEncodableList(const EncodableList& list) {
  Diagnostics decoded(
    std::any_cast<const ReaderConnectionStatus&>(std::get<CustomEncodableValue>(list[0])),
    list[1].LongValue(),
    std::get<bool>(list[6]));
  auto& encodable_last_error_code = list[2];
  if (!encodable_last_error_code.IsNull()) {
    decoded.set_last_error_code(std::any_cast<const ReaderErrorCode&>(std::get<CustomEncodableValue>(encodable_last_error_code)));
  }
  auto& encodable_last_error_message = list[3];
  if (!encodable_last_error_message.IsNull()) {
    decoded.set_last_error_message(std::get<std::string>(encodable_last_error_message));
  }
  auto& encodable_last_connect_start_ms = list[4];
  if (!encodable_last_connect_start_ms.IsNull()) {
    decoded.set_last_connect_start_ms(encodable_last_connect_start_ms.LongValue());
  }
  auto& encodable_last_connect_duration_ms = list[5];
  if (!encodable_last_connect_duration_ms.IsNull()) {
    decoded.set_last_connect_duration_ms(encodable_last_connect_duration_ms.LongValue());
  }
  auto& encodable_scanning_enabled = list[7];
  if (!encodable_scanning_enabled.IsNull()) {
    decoded.set_scanning_enabled(std::get<bool>(encodable_scanning_enabled));
  }
  auto& encodable_scanning_enabled_last_toggle_ms = list[8];
  if (!encodable_scanning_enabled_last_toggle_ms.IsNull()) {
    decoded.set_scanning_enabled_last_toggle_ms(encodable_scanning_enabled_last_toggle_ms.LongValue());
  }
  auto& encodable_inventory_active = list[9];
  if (!encodable_inventory_active.IsNull()) {
    decoded.set_inventory_active(std::get<bool>(encodable_inventory_active));
  }
  auto& encodable_last_inventory_start_ms = list[10];
  if (!encodable_last_inventory_start_ms.IsNull()) {
    decoded.set_last_inventory_start_ms(encodable_last_inventory_start_ms.LongValue());
  }
  auto& encodable_last_inventory_stop_ms = list[11];
  if (!encodable_last_inventory_stop_ms.IsNull()) {
    decoded.set_last_inventory_stop_ms(encodable_last_inventory_stop_ms.LongValue());
  }
  auto& encodable_pending_purge_active = list[12];
  if (!encodable_pending_purge_active.IsNull()) {
    decoded.set_pending_purge_active(std::get<bool>(encodable_pending_purge_active));
  }
  auto& encodable_last_inventory_stop_reason = list[13];
  if (!encodable_last_inventory_stop_reason.IsNull()) {
    decoded.set_last_inventory_stop_reason(std::get<std::string>(encodable_last_inventory_stop_reason));
  }
  auto& encodable_last_inventory_start_reason = list[14];
  if (!encodable_last_inventory_start_reason.IsNull()) {
    decoded.set_last_inventory_start_reason(std::get<std::string>(encodable_last_inventory_start_reason));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ReaderConnectionType>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ReaderConnectionStatus>(enum_arg_value));
      }
    case 131: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<BluetoothScanStatus>(enum_arg_value));
      }
    case 132: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ReaderErrorCode>(enum_arg_value));
      }
    case 133: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ReaderConfigBatchMode>(enum_arg_value));
      }
    case 134: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ReaderBeeperVolume>(enum_arg_value));
      }
    case 135: {
        return CustomEncodableValue(ReaderError::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 136: {
        return CustomEncodableValue(Reader::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 137: {
        return CustomEncodableValue(BluetoothDevice::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 138: {
        return CustomEncodableValue(ReaderConfig::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 139: {
        return CustomEncodableValue(ReaderInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 140: {
        return CustomEncodableValue(ReaderRegion::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 141: {
        return CustomEncodableValue(RfidTag::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 142: {
        return CustomEncodableValue(BatteryData::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 143: {
        return CustomEncodableValue(Diagnostics::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(ReaderConnectionType)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ReaderConnectionType>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ReaderConnectionStatus)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ReaderConnectionStatus>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(BluetoothScanStatus)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<BluetoothScanStatus>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ReaderErrorCode)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ReaderErrorCode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ReaderConfigBatchMode)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ReaderConfigBatchMode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ReaderBeeperVolume)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ReaderBeeperVolume>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ReaderError)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<ReaderError>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(Reader)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<Reader>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(BluetoothDevice)) {
      stream->WriteByte(137);
      WriteValue(EncodableValue(std::any_cast<BluetoothDevice>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ReaderConfig)) {
      stream->WriteByte(138);
      WriteValue(EncodableValue(std::any_cast<ReaderConfig>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ReaderInfo)) {
      stream->WriteByte(139);
      WriteValue(EncodableValue(std::any_cast<ReaderInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ReaderRegion)) {
      stream->WriteByte(140);
      WriteValue(EncodableValue(std::any_cast<ReaderRegion>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(RfidTag)) {
      stream->WriteByte(141);
      WriteValue(EncodableValue(std::any_cast<RfidTag>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(BatteryData)) {
      stream->WriteByte(142);
      WriteValue(EncodableValue(std::any_cast<BatteryData>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(Diagnostics)) {
      stream->WriteByte(143);
      WriteValue(EncodableValue(std::any_cast<Diagnostics>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by FlutterZebraRfid.
const flutter::StandardMessageCodec& FlutterZebraRfid::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `FlutterZebraRfid` to handle messages through the `binary_messenger`.
void FlutterZebraRfid::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  FlutterZebraRfid* api) {
  FlutterZebraRfid::SetUp(binary_messenger, api, "");
}

void FlutterZebraRfid::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  FlutterZebraRfid* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.updateAvailableReaders" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_connection_type_arg = args.at(0);
          if (encodable_connection_type_arg.IsNull()) {
            reply(WrapError("connection_type_arg unexpectedly null."));
            return;
          }
          const auto& connection_type_arg = std::any_cast<const ReaderConnectionType&>(std::get<CustomEncodableValue>(encodable_connection_type_arg));
          api->UpdateAvailableReaders(connection_type_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.startBluetoothScan" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->StartBluetoothScan([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.stopBluetoothScan" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->StopBluetoothScan([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.getBondedDevices" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetBondedDevices([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.pairBluetoothDevice" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_address_arg = args.at(0);
          if (encodable_address_arg.IsNull()) {
            reply(WrapError("address_arg unexpectedly null."));
            return;
          }
          const auto& address_arg = std::get<std::string>(encodable_address_arg);
          api->PairBluetoothDevice(address_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.connectReader" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_reader_id_arg = args.at(0);
          if (encodable_reader_id_arg.IsNull()) {
            reply(WrapError("reader_id_arg unexpectedly null."));
            return;
          }
          const int64_t reader_id_arg = encodable_reader_id_arg.LongValue();
          api->ConnectReader(reader_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.configureReader" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_config_arg = args.at(0);
          if (encodable_config_arg.IsNull()) {
            reply(WrapError("config_arg unexpectedly null."));
            return;
          }
          const auto& config_arg = std::any_cast<const ReaderConfig&>(std::get<CustomEncodableValue>(encodable_config_arg));
          const auto& encodable_should_persist_arg = args.at(1);
          if (encodable_should_persist_arg.IsNull()) {
            reply(WrapError("should_persist_arg unexpectedly null."));
            return;
          }
          const auto& should_persist_arg = std::get<bool>(encodable_should_persist_arg);
          api->ConfigureReader(config_arg, should_persist_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.disconnectReader" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->DisconnectReader([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.triggerDeviceStatus" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->TriggerDeviceStatus([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.startLocating" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_tags_arg = args.at(0);
          if (encodable_tags_arg.IsNull()) {
            reply(WrapError("tags_arg unexpectedly null."));
            return;
          }
          const auto& tags_arg = std::get<EncodableList>(encodable_tags_arg);
          const auto& encodable_disable_beep_arg = args.at(1);
          const auto* disable_beep_arg = std::get_if<bool>(&encodable_disable_beep_arg);
          api->StartLocating(tags_arg, disable_beep_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.stopLocating" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->StopLocating([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.resetLocateState" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->ResetLocateState([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.currentReader" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<std::optional<Reader>> output = api->CurrentReader();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          auto output_optional = std::move(output).TakeValue();
          if (output_optional) {
            wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
          } else {
            wrapped.push_back(EncodableValue());
          }
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.readerConfig" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->ReaderConfig([reply](ErrorOr<ReaderConfig>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.supportedReaderRegions" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->SupportedReaderRegions([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.setReaderRegion" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_region_code_arg = args.at(0);
          if (encodable_region_code_arg.IsNull()) {
            reply(WrapError("region_code_arg unexpectedly null."));
            return;
          }
          const auto& region_code_arg = std::get<std::string>(encodable_region_code_arg);
          api->SetReaderRegion(region_code_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.diagnostics" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->Diagnostics([reply](ErrorOr<Diagnostics>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.setScanningEnabled" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_enabled_arg = args.at(0);
          if (encodable_enabled_arg.IsNull()) {
            reply(WrapError("enabled_arg unexpectedly null."));
            return;
          }
          const auto& enabled_arg = std::get<bool>(encodable_enabled_arg);
          api->SetScanningEnabled(enabled_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue FlutterZebraRfid::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue FlutterZebraRfid::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
FlutterZebraRfidCallbacks::FlutterZebraRfidCallbacks(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

FlutterZebraRfidCallbacks::FlutterZebraRfidCallbacks(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& FlutterZebraRfidCallbacks::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void FlutterZebraRfidCallbacks::OnAvailableReadersChanged(
  const EncodableList& readers_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onAvailableReadersChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(readers_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraRfidCallbacks::OnReaderConnectionStatusChanged(
  const ReaderConnectionStatus& status_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onReaderConnectionStatusChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(status_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraRfidCallbacks::OnTagsRead(
  const EncodableList& tags_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onTagsRead" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(tags_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraRfidCallbacks::OnBatteryDataReceived(
  const BatteryData& battery_data_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onBatteryDataReceived" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(battery_data_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraRfidCallbacks::OnTagsLocated(
  const EncodableList& tags_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onTagsLocated" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(tags_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraRfidCallbacks::OnBluetoothDeviceDiscovered(
  const BluetoothDevice& device_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onBluetoothDeviceDiscovered" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(device_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraRfidCallbacks::OnBluetoothScanStatusChanged(
  const BluetoothScanStatus& status_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onBluetoothScanStatusChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(status_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraRfidCallbacks::OnBluetoothPairingResult(
  const BluetoothDevice& device_arg,
  bool success_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onBluetoothPairingResult" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(device_arg),
    EncodableValue(success_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

void FlutterZebraRfidCallbacks::OnReaderConnectionError(
  const ReaderError& error_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onReaderConnectionError" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(error_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }

  });
}

}  // namespace flutter_zebra_rfid
