// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class FlutterCaptureError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "FlutterCaptureError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? FlutterCaptureError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterCaptureError {
  return FlutterCaptureError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum CaptureDeviceStatus: Int {
  case connecting = 0
  case connected = 1
  case degraded = 2
  case disconnecting = 3
  case disconnected = 4
  case error = 5
}

enum CaptureCapabilityStatus: Int {
  case unavailable = 0
  case disconnected = 1
  case connecting = 2
  case connected = 3
  case error = 4
}

enum CaptureCapabilityType: Int {
  case rfid = 0
  case barcode = 1
}

enum CaptureDeviceTopology: Int {
  case bluetoothComboReader = 0
  case tc22RfidSled = 1
  case externalRfidWithTerminalBarcode = 2
  case rfidOnly = 3
  case barcodeOnly = 4
  case unknown = 5
}

enum CaptureMatchConfidence: Int {
  case exact = 0
  case high = 1
  case medium = 2
  case low = 3
  case manual = 4
}

enum CaptureBarcodeSource: Int {
  case builtInTerminal = 0
  case rfidSled = 1
  case externalBluetooth = 2
  case externalUsb = 3
  case unknown = 4
}

enum CaptureBarcodeMode: Int {
  case auto = 0
  case dataWedge = 1
  case scannerSdk = 2
}

enum CaptureReaderConfigBatchMode: Int {
  case auto = 0
  case enabled = 1
  case disabled = 2
}

enum CaptureReaderBeeperVolume: Int {
  case quiet = 0
  case low = 1
  case medium = 2
  case high = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct CaptureReaderConfig {
  var transmitPowerIndex: Int64? = nil
  var tari: Int64? = nil
  var beeperVolume: CaptureReaderBeeperVolume? = nil
  var enableDynamicPower: Bool? = nil
  var enableLedBlink: Bool? = nil
  var batchMode: CaptureReaderConfigBatchMode? = nil
  var scanBatchMode: CaptureReaderConfigBatchMode? = nil
  var rfModeTableIndex: Int64? = nil
  var receiveSensitivityIndex: Int64? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureReaderConfig? {
    let transmitPowerIndex: Int64? = isNullish(pigeonVar_list[0]) ? nil : (pigeonVar_list[0] is Int64? ? pigeonVar_list[0] as! Int64? : Int64(pigeonVar_list[0] as! Int32))
    let tari: Int64? = isNullish(pigeonVar_list[1]) ? nil : (pigeonVar_list[1] is Int64? ? pigeonVar_list[1] as! Int64? : Int64(pigeonVar_list[1] as! Int32))
    let beeperVolume: CaptureReaderBeeperVolume? = nilOrValue(pigeonVar_list[2])
    let enableDynamicPower: Bool? = nilOrValue(pigeonVar_list[3])
    let enableLedBlink: Bool? = nilOrValue(pigeonVar_list[4])
    let batchMode: CaptureReaderConfigBatchMode? = nilOrValue(pigeonVar_list[5])
    let scanBatchMode: CaptureReaderConfigBatchMode? = nilOrValue(pigeonVar_list[6])
    let rfModeTableIndex: Int64? = isNullish(pigeonVar_list[7]) ? nil : (pigeonVar_list[7] is Int64? ? pigeonVar_list[7] as! Int64? : Int64(pigeonVar_list[7] as! Int32))
    let receiveSensitivityIndex: Int64? = isNullish(pigeonVar_list[8]) ? nil : (pigeonVar_list[8] is Int64? ? pigeonVar_list[8] as! Int64? : Int64(pigeonVar_list[8] as! Int32))

    return CaptureReaderConfig(
      transmitPowerIndex: transmitPowerIndex,
      tari: tari,
      beeperVolume: beeperVolume,
      enableDynamicPower: enableDynamicPower,
      enableLedBlink: enableLedBlink,
      batchMode: batchMode,
      scanBatchMode: scanBatchMode,
      rfModeTableIndex: rfModeTableIndex,
      receiveSensitivityIndex: receiveSensitivityIndex
    )
  }
  func toList() -> [Any?] {
    return [
      transmitPowerIndex,
      tari,
      beeperVolume,
      enableDynamicPower,
      enableLedBlink,
      batchMode,
      scanBatchMode,
      rfModeTableIndex,
      receiveSensitivityIndex,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CaptureRfidCapability {
  var readerId: Int64
  var hardwareIdentity: String
  var displayName: String
  var status: CaptureCapabilityStatus
  var model: String? = nil
  var serialNumber: String? = nil
  var error: String? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureRfidCapability? {
    let readerId = pigeonVar_list[0] is Int64 ? pigeonVar_list[0] as! Int64 : Int64(pigeonVar_list[0] as! Int32)
    let hardwareIdentity = pigeonVar_list[1] as! String
    let displayName = pigeonVar_list[2] as! String
    let status = pigeonVar_list[3] as! CaptureCapabilityStatus
    let model: String? = nilOrValue(pigeonVar_list[4])
    let serialNumber: String? = nilOrValue(pigeonVar_list[5])
    let error: String? = nilOrValue(pigeonVar_list[6])

    return CaptureRfidCapability(
      readerId: readerId,
      hardwareIdentity: hardwareIdentity,
      displayName: displayName,
      status: status,
      model: model,
      serialNumber: serialNumber,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      readerId,
      hardwareIdentity,
      displayName,
      status,
      model,
      serialNumber,
      error,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CaptureBarcodeCapability {
  var endpointId: String
  var displayName: String
  var source: CaptureBarcodeSource
  var mode: CaptureBarcodeMode
  var status: CaptureCapabilityStatus
  var preferred: Bool
  var scannerId: Int64? = nil
  var model: String? = nil
  var serialNumber: String? = nil
  var error: String? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureBarcodeCapability? {
    let endpointId = pigeonVar_list[0] as! String
    let displayName = pigeonVar_list[1] as! String
    let source = pigeonVar_list[2] as! CaptureBarcodeSource
    let mode = pigeonVar_list[3] as! CaptureBarcodeMode
    let status = pigeonVar_list[4] as! CaptureCapabilityStatus
    let preferred = pigeonVar_list[5] as! Bool
    let scannerId: Int64? = isNullish(pigeonVar_list[6]) ? nil : (pigeonVar_list[6] is Int64? ? pigeonVar_list[6] as! Int64? : Int64(pigeonVar_list[6] as! Int32))
    let model: String? = nilOrValue(pigeonVar_list[7])
    let serialNumber: String? = nilOrValue(pigeonVar_list[8])
    let error: String? = nilOrValue(pigeonVar_list[9])

    return CaptureBarcodeCapability(
      endpointId: endpointId,
      displayName: displayName,
      source: source,
      mode: mode,
      status: status,
      preferred: preferred,
      scannerId: scannerId,
      model: model,
      serialNumber: serialNumber,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      endpointId,
      displayName,
      source,
      mode,
      status,
      preferred,
      scannerId,
      model,
      serialNumber,
      error,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CaptureDevice {
  var id: String
  var displayName: String
  var topology: CaptureDeviceTopology
  var status: CaptureDeviceStatus
  var matchConfidence: CaptureMatchConfidence
  var matchReason: String
  var active: Bool
  var rfid: CaptureRfidCapability? = nil
  var barcode: CaptureBarcodeCapability? = nil
  var lastError: String? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureDevice? {
    let id = pigeonVar_list[0] as! String
    let displayName = pigeonVar_list[1] as! String
    let topology = pigeonVar_list[2] as! CaptureDeviceTopology
    let status = pigeonVar_list[3] as! CaptureDeviceStatus
    let matchConfidence = pigeonVar_list[4] as! CaptureMatchConfidence
    let matchReason = pigeonVar_list[5] as! String
    let active = pigeonVar_list[6] as! Bool
    let rfid: CaptureRfidCapability? = nilOrValue(pigeonVar_list[7])
    let barcode: CaptureBarcodeCapability? = nilOrValue(pigeonVar_list[8])
    let lastError: String? = nilOrValue(pigeonVar_list[9])

    return CaptureDevice(
      id: id,
      displayName: displayName,
      topology: topology,
      status: status,
      matchConfidence: matchConfidence,
      matchReason: matchReason,
      active: active,
      rfid: rfid,
      barcode: barcode,
      lastError: lastError
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      displayName,
      topology,
      status,
      matchConfidence,
      matchReason,
      active,
      rfid,
      barcode,
      lastError,
    ]
  }
}

private class FlutterZebraCapturePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CaptureDeviceStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CaptureCapabilityStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CaptureCapabilityType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CaptureDeviceTopology(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CaptureMatchConfidence(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CaptureBarcodeSource(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CaptureBarcodeMode(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CaptureReaderConfigBatchMode(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CaptureReaderBeeperVolume(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      return CaptureReaderConfig.fromList(self.readValue() as! [Any?])
    case 139:
      return CaptureRfidCapability.fromList(self.readValue() as! [Any?])
    case 140:
      return CaptureBarcodeCapability.fromList(self.readValue() as! [Any?])
    case 141:
      return CaptureDevice.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FlutterZebraCapturePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CaptureDeviceStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CaptureCapabilityStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? CaptureCapabilityType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? CaptureDeviceTopology {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? CaptureMatchConfidence {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? CaptureBarcodeSource {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? CaptureBarcodeMode {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? CaptureReaderConfigBatchMode {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? CaptureReaderBeeperVolume {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? CaptureReaderConfig {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? CaptureRfidCapability {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? CaptureBarcodeCapability {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? CaptureDevice {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FlutterZebraCapturePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterZebraCapturePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterZebraCapturePigeonCodecWriter(data: data)
  }
}

class FlutterZebraCapturePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FlutterZebraCapturePigeonCodec(readerWriter: FlutterZebraCapturePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterZebraCapture {
  func refreshCaptureDevices(completion: @escaping (Result<Void, Error>) -> Void)
  func connectCaptureDevice(captureDeviceId: String, rfidConfig: CaptureReaderConfig?, completion: @escaping (Result<Void, Error>) -> Void)
  func disconnectCaptureDevice(captureDeviceId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func setCaptureDeviceBarcodeOverride(captureDeviceId: String, barcodeEndpointId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func configureCaptureDevice(captureDeviceId: String, rfidConfig: CaptureReaderConfig, shouldPersist: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func setCaptureDeviceForeground(foreground: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func activeCaptureDevice() throws -> CaptureDevice?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterZebraCaptureSetup {
  static var codec: FlutterStandardMessageCodec { FlutterZebraCapturePigeonCodec.shared }
  /// Sets up an instance of `FlutterZebraCapture` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterZebraCapture?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let refreshCaptureDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.refreshCaptureDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      refreshCaptureDevicesChannel.setMessageHandler { _, reply in
        api.refreshCaptureDevices { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      refreshCaptureDevicesChannel.setMessageHandler(nil)
    }
    let connectCaptureDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.connectCaptureDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectCaptureDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let captureDeviceIdArg = args[0] as! String
        let rfidConfigArg: CaptureReaderConfig? = nilOrValue(args[1])
        api.connectCaptureDevice(captureDeviceId: captureDeviceIdArg, rfidConfig: rfidConfigArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectCaptureDeviceChannel.setMessageHandler(nil)
    }
    let disconnectCaptureDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.disconnectCaptureDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectCaptureDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let captureDeviceIdArg = args[0] as! String
        api.disconnectCaptureDevice(captureDeviceId: captureDeviceIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectCaptureDeviceChannel.setMessageHandler(nil)
    }
    let setCaptureDeviceBarcodeOverrideChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.setCaptureDeviceBarcodeOverride\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCaptureDeviceBarcodeOverrideChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let captureDeviceIdArg = args[0] as! String
        let barcodeEndpointIdArg = args[1] as! String
        api.setCaptureDeviceBarcodeOverride(captureDeviceId: captureDeviceIdArg, barcodeEndpointId: barcodeEndpointIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setCaptureDeviceBarcodeOverrideChannel.setMessageHandler(nil)
    }
    let configureCaptureDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.configureCaptureDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureCaptureDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let captureDeviceIdArg = args[0] as! String
        let rfidConfigArg = args[1] as! CaptureReaderConfig
        let shouldPersistArg = args[2] as! Bool
        api.configureCaptureDevice(captureDeviceId: captureDeviceIdArg, rfidConfig: rfidConfigArg, shouldPersist: shouldPersistArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureCaptureDeviceChannel.setMessageHandler(nil)
    }
    let setCaptureDeviceForegroundChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.setCaptureDeviceForeground\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCaptureDeviceForegroundChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let foregroundArg = args[0] as! Bool
        api.setCaptureDeviceForeground(foreground: foregroundArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setCaptureDeviceForegroundChannel.setMessageHandler(nil)
    }
    let activeCaptureDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.activeCaptureDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      activeCaptureDeviceChannel.setMessageHandler { _, reply in
        do {
          let result = try api.activeCaptureDevice()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      activeCaptureDeviceChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FlutterZebraCaptureCallbacksProtocol {
  func onAvailableCaptureDevicesChanged(devices devicesArg: [CaptureDevice], completion: @escaping (Result<Void, FlutterCaptureError>) -> Void)
  func onActiveCaptureDeviceChanged(device deviceArg: CaptureDevice?, completion: @escaping (Result<Void, FlutterCaptureError>) -> Void)
  func onCaptureDeviceStatusChanged(device deviceArg: CaptureDevice, completion: @escaping (Result<Void, FlutterCaptureError>) -> Void)
}
class FlutterZebraCaptureCallbacks: FlutterZebraCaptureCallbacksProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FlutterZebraCapturePigeonCodec {
    return FlutterZebraCapturePigeonCodec.shared
  }
  func onAvailableCaptureDevicesChanged(devices devicesArg: [CaptureDevice], completion: @escaping (Result<Void, FlutterCaptureError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onAvailableCaptureDevicesChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([devicesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterCaptureError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onActiveCaptureDeviceChanged(device deviceArg: CaptureDevice?, completion: @escaping (Result<Void, FlutterCaptureError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onActiveCaptureDeviceChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterCaptureError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onCaptureDeviceStatusChanged(device deviceArg: CaptureDevice, completion: @escaping (Result<Void, FlutterCaptureError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onCaptureDeviceStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterCaptureError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
