// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class FlutterRfidError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "FlutterRfidError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? FlutterRfidError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterRfidError {
  return FlutterRfidError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum ReaderConnectionType: Int {
  case bluetooth = 0
  case usb = 1
  case ip = 2
  case all = 3
}

enum ReaderConnectionStatus: Int {
  case connecting = 0
  case connected = 1
  case disconnecting = 2
  case disconnected = 3
  case error = 4
}

enum BluetoothScanStatus: Int {
  case scanning = 0
  case finished = 1
  case error = 2
}

enum ReaderErrorCode: Int {
  case unknown = 0
  case noAvailableReaders = 1
  case invalidReaderIndex = 2
  case readerDeviceNull = 3
  case alreadyConnecting = 4
  case notConnected = 5
  case sdkInvalidUsage = 6
  case sdkOperationFailure = 7
  case timeout = 8
}

enum ReaderConfigBatchMode: Int {
  case auto = 0
  case enabled = 1
  case disabled = 2
}

enum ReaderBeeperVolume: Int {
  case quiet = 0
  case low = 1
  case medium = 2
  case high = 3
}

enum WifiSecurity: Int {
  case open = 0
  case wpaPersonal = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReaderError {
  var code: ReaderErrorCode
  var message: String
  var details: String? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReaderError? {
    let code = pigeonVar_list[0] as! ReaderErrorCode
    let message = pigeonVar_list[1] as! String
    let details: String? = nilOrValue(pigeonVar_list[2])

    return ReaderError(
      code: code,
      message: message,
      details: details
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      details,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Reader {
  var name: String? = nil
  var id: Int64
  var info: ReaderInfo? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Reader? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let id = pigeonVar_list[1] is Int64 ? pigeonVar_list[1] as! Int64 : Int64(pigeonVar_list[1] as! Int32)
    let info: ReaderInfo? = nilOrValue(pigeonVar_list[2])

    return Reader(
      name: name,
      id: id,
      info: info
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      id,
      info,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BluetoothDevice {
  var name: String? = nil
  var address: String
  var isPaired: Bool



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BluetoothDevice? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let address = pigeonVar_list[1] as! String
    let isPaired = pigeonVar_list[2] as! Bool

    return BluetoothDevice(
      name: name,
      address: address,
      isPaired: isPaired
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      address,
      isPaired,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReaderConfig {
  var transmitPowerIndex: Int64? = nil
  var tari: Int64? = nil
  var beeperVolume: ReaderBeeperVolume? = nil
  var enableDynamicPower: Bool? = nil
  var enableLedBlink: Bool? = nil
  var batchMode: ReaderConfigBatchMode? = nil
  var scanBatchMode: ReaderConfigBatchMode? = nil
  var rfModeTableIndex: Int64? = nil
  var receiveSensitivityIndex: Int64? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReaderConfig? {
    let transmitPowerIndex: Int64? = isNullish(pigeonVar_list[0]) ? nil : (pigeonVar_list[0] is Int64? ? pigeonVar_list[0] as! Int64? : Int64(pigeonVar_list[0] as! Int32))
    let tari: Int64? = isNullish(pigeonVar_list[1]) ? nil : (pigeonVar_list[1] is Int64? ? pigeonVar_list[1] as! Int64? : Int64(pigeonVar_list[1] as! Int32))
    let beeperVolume: ReaderBeeperVolume? = nilOrValue(pigeonVar_list[2])
    let enableDynamicPower: Bool? = nilOrValue(pigeonVar_list[3])
    let enableLedBlink: Bool? = nilOrValue(pigeonVar_list[4])
    let batchMode: ReaderConfigBatchMode? = nilOrValue(pigeonVar_list[5])
    let scanBatchMode: ReaderConfigBatchMode? = nilOrValue(pigeonVar_list[6])
    let rfModeTableIndex: Int64? = isNullish(pigeonVar_list[7]) ? nil : (pigeonVar_list[7] is Int64? ? pigeonVar_list[7] as! Int64? : Int64(pigeonVar_list[7] as! Int32))
    let receiveSensitivityIndex: Int64? = isNullish(pigeonVar_list[8]) ? nil : (pigeonVar_list[8] is Int64? ? pigeonVar_list[8] as! Int64? : Int64(pigeonVar_list[8] as! Int32))

    return ReaderConfig(
      transmitPowerIndex: transmitPowerIndex,
      tari: tari,
      beeperVolume: beeperVolume,
      enableDynamicPower: enableDynamicPower,
      enableLedBlink: enableLedBlink,
      batchMode: batchMode,
      scanBatchMode: scanBatchMode,
      rfModeTableIndex: rfModeTableIndex,
      receiveSensitivityIndex: receiveSensitivityIndex
    )
  }
  func toList() -> [Any?] {
    return [
      transmitPowerIndex,
      tari,
      beeperVolume,
      enableDynamicPower,
      enableLedBlink,
      batchMode,
      scanBatchMode,
      rfModeTableIndex,
      receiveSensitivityIndex,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WifiConfig {
  var ssid: String
  var password: String? = nil
  var security: WifiSecurity
  var connectAfterSave: Bool
  var persist: Bool



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WifiConfig? {
    let ssid = pigeonVar_list[0] as! String
    let password: String? = nilOrValue(pigeonVar_list[1])
    let security = pigeonVar_list[2] as! WifiSecurity
    let connectAfterSave = pigeonVar_list[3] as! Bool
    let persist = pigeonVar_list[4] as! Bool

    return WifiConfig(
      ssid: ssid,
      password: password,
      security: security,
      connectAfterSave: connectAfterSave,
      persist: persist
    )
  }
  func toList() -> [Any?] {
    return [
      ssid,
      password,
      security,
      connectAfterSave,
      persist,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WifiStatus {
  var status: String? = nil
  var ssid: String? = nil
  var ipAddress: String? = nil
  var macAddress: String? = nil
  var properties: [String?: String?]



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WifiStatus? {
    let status: String? = nilOrValue(pigeonVar_list[0])
    let ssid: String? = nilOrValue(pigeonVar_list[1])
    let ipAddress: String? = nilOrValue(pigeonVar_list[2])
    let macAddress: String? = nilOrValue(pigeonVar_list[3])
    let properties = pigeonVar_list[4] as! [String?: String?]

    return WifiStatus(
      status: status,
      ssid: ssid,
      ipAddress: ipAddress,
      macAddress: macAddress,
      properties: properties
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      ssid,
      ipAddress,
      macAddress,
      properties,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReaderInfo {
  var transmitPowerLevels: [Any?]
  var firmwareVersion: String? = nil
  var modelVersion: String? = nil
  var scannerName: String? = nil
  var serialNumber: String? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReaderInfo? {
    let transmitPowerLevels = pigeonVar_list[0] as! [Any?]
    let firmwareVersion: String? = nilOrValue(pigeonVar_list[1])
    let modelVersion: String? = nilOrValue(pigeonVar_list[2])
    let scannerName: String? = nilOrValue(pigeonVar_list[3])
    let serialNumber: String? = nilOrValue(pigeonVar_list[4])

    return ReaderInfo(
      transmitPowerLevels: transmitPowerLevels,
      firmwareVersion: firmwareVersion,
      modelVersion: modelVersion,
      scannerName: scannerName,
      serialNumber: serialNumber
    )
  }
  func toList() -> [Any?] {
    return [
      transmitPowerLevels,
      firmwareVersion,
      modelVersion,
      scannerName,
      serialNumber,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReaderRegion {
  var code: String
  var name: String? = nil
  var standardName: String? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReaderRegion? {
    let code = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let standardName: String? = nilOrValue(pigeonVar_list[2])

    return ReaderRegion(
      code: code,
      name: name,
      standardName: standardName
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      name,
      standardName,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RfidTag {
  var id: String
  var rssi: Int64
  var relativeDistance: Double? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RfidTag? {
    let id = pigeonVar_list[0] as! String
    let rssi = pigeonVar_list[1] is Int64 ? pigeonVar_list[1] as! Int64 : Int64(pigeonVar_list[1] as! Int32)
    let relativeDistance: Double? = nilOrValue(pigeonVar_list[2])

    return RfidTag(
      id: id,
      rssi: rssi,
      relativeDistance: relativeDistance
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      rssi,
      relativeDistance,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BatteryData {
  var level: Int64
  var isCharging: Bool
  var cause: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BatteryData? {
    let level = pigeonVar_list[0] is Int64 ? pigeonVar_list[0] as! Int64 : Int64(pigeonVar_list[0] as! Int32)
    let isCharging = pigeonVar_list[1] as! Bool
    let cause = pigeonVar_list[2] as! String

    return BatteryData(
      level: level,
      isCharging: isCharging,
      cause: cause
    )
  }
  func toList() -> [Any?] {
    return [
      level,
      isCharging,
      cause,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Diagnostics {
  var connectionState: ReaderConnectionStatus
  var connectAttempts: Int64
  var lastErrorCode: ReaderErrorCode? = nil
  var lastErrorMessage: String? = nil
  var lastConnectStartMs: Int64? = nil
  var lastConnectDurationMs: Int64? = nil
  var isLocating: Bool
  var scanningEnabled: Bool? = nil
  var scanningEnabledLastToggleMs: Int64? = nil
  var inventoryActive: Bool? = nil
  var lastInventoryStartMs: Int64? = nil
  var lastInventoryStopMs: Int64? = nil
  var pendingPurgeActive: Bool? = nil
  var lastInventoryStopReason: String? = nil
  var lastInventoryStartReason: String? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Diagnostics? {
    let connectionState = pigeonVar_list[0] as! ReaderConnectionStatus
    let connectAttempts = pigeonVar_list[1] is Int64 ? pigeonVar_list[1] as! Int64 : Int64(pigeonVar_list[1] as! Int32)
    let lastErrorCode: ReaderErrorCode? = nilOrValue(pigeonVar_list[2])
    let lastErrorMessage: String? = nilOrValue(pigeonVar_list[3])
    let lastConnectStartMs: Int64? = isNullish(pigeonVar_list[4]) ? nil : (pigeonVar_list[4] is Int64? ? pigeonVar_list[4] as! Int64? : Int64(pigeonVar_list[4] as! Int32))
    let lastConnectDurationMs: Int64? = isNullish(pigeonVar_list[5]) ? nil : (pigeonVar_list[5] is Int64? ? pigeonVar_list[5] as! Int64? : Int64(pigeonVar_list[5] as! Int32))
    let isLocating = pigeonVar_list[6] as! Bool
    let scanningEnabled: Bool? = nilOrValue(pigeonVar_list[7])
    let scanningEnabledLastToggleMs: Int64? = isNullish(pigeonVar_list[8]) ? nil : (pigeonVar_list[8] is Int64? ? pigeonVar_list[8] as! Int64? : Int64(pigeonVar_list[8] as! Int32))
    let inventoryActive: Bool? = nilOrValue(pigeonVar_list[9])
    let lastInventoryStartMs: Int64? = isNullish(pigeonVar_list[10]) ? nil : (pigeonVar_list[10] is Int64? ? pigeonVar_list[10] as! Int64? : Int64(pigeonVar_list[10] as! Int32))
    let lastInventoryStopMs: Int64? = isNullish(pigeonVar_list[11]) ? nil : (pigeonVar_list[11] is Int64? ? pigeonVar_list[11] as! Int64? : Int64(pigeonVar_list[11] as! Int32))
    let pendingPurgeActive: Bool? = nilOrValue(pigeonVar_list[12])
    let lastInventoryStopReason: String? = nilOrValue(pigeonVar_list[13])
    let lastInventoryStartReason: String? = nilOrValue(pigeonVar_list[14])

    return Diagnostics(
      connectionState: connectionState,
      connectAttempts: connectAttempts,
      lastErrorCode: lastErrorCode,
      lastErrorMessage: lastErrorMessage,
      lastConnectStartMs: lastConnectStartMs,
      lastConnectDurationMs: lastConnectDurationMs,
      isLocating: isLocating,
      scanningEnabled: scanningEnabled,
      scanningEnabledLastToggleMs: scanningEnabledLastToggleMs,
      inventoryActive: inventoryActive,
      lastInventoryStartMs: lastInventoryStartMs,
      lastInventoryStopMs: lastInventoryStopMs,
      pendingPurgeActive: pendingPurgeActive,
      lastInventoryStopReason: lastInventoryStopReason,
      lastInventoryStartReason: lastInventoryStartReason
    )
  }
  func toList() -> [Any?] {
    return [
      connectionState,
      connectAttempts,
      lastErrorCode,
      lastErrorMessage,
      lastConnectStartMs,
      lastConnectDurationMs,
      isLocating,
      scanningEnabled,
      scanningEnabledLastToggleMs,
      inventoryActive,
      lastInventoryStartMs,
      lastInventoryStopMs,
      pendingPurgeActive,
      lastInventoryStopReason,
      lastInventoryStartReason,
    ]
  }
}

private class FlutterZebraRfidPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return ReaderConnectionType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return ReaderConnectionStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return BluetoothScanStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return ReaderErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return ReaderConfigBatchMode(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return ReaderBeeperVolume(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return WifiSecurity(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      return ReaderError.fromList(self.readValue() as! [Any?])
    case 137:
      return Reader.fromList(self.readValue() as! [Any?])
    case 138:
      return BluetoothDevice.fromList(self.readValue() as! [Any?])
    case 139:
      return ReaderConfig.fromList(self.readValue() as! [Any?])
    case 140:
      return WifiConfig.fromList(self.readValue() as! [Any?])
    case 141:
      return WifiStatus.fromList(self.readValue() as! [Any?])
    case 142:
      return ReaderInfo.fromList(self.readValue() as! [Any?])
    case 143:
      return ReaderRegion.fromList(self.readValue() as! [Any?])
    case 144:
      return RfidTag.fromList(self.readValue() as! [Any?])
    case 145:
      return BatteryData.fromList(self.readValue() as! [Any?])
    case 146:
      return Diagnostics.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FlutterZebraRfidPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ReaderConnectionType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ReaderConnectionStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? BluetoothScanStatus {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? ReaderErrorCode {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? ReaderConfigBatchMode {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? ReaderBeeperVolume {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? WifiSecurity {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? ReaderError {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? Reader {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? BluetoothDevice {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ReaderConfig {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? WifiConfig {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? WifiStatus {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? ReaderInfo {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? ReaderRegion {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? RfidTag {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? BatteryData {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? Diagnostics {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FlutterZebraRfidPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterZebraRfidPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterZebraRfidPigeonCodecWriter(data: data)
  }
}

class FlutterZebraRfidPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FlutterZebraRfidPigeonCodec(readerWriter: FlutterZebraRfidPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterZebraRfid {
  /// Returns list with names of available readers for specified `connectionType`.
  func updateAvailableReaders(connectionType: ReaderConnectionType, completion: @escaping (Result<Void, Error>) -> Void)
  /// Starts Bluetooth classic device discovery for pairing.
  func startBluetoothScan(completion: @escaping (Result<Void, Error>) -> Void)
  /// Stops Bluetooth classic device discovery.
  func stopBluetoothScan(completion: @escaping (Result<Void, Error>) -> Void)
  /// Returns currently bonded Bluetooth devices.
  func getBondedDevices(completion: @escaping (Result<[BluetoothDevice], Error>) -> Void)
  /// Starts pairing with the Bluetooth device at `address`.
  func pairBluetoothDevice(address: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Connects to a reader with `readerId` ID.
  func connectReader(readerId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Connects directly to a network reader by IP address or host name.
  func connectReaderByIp(host: String, port: Int64?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Configures reader with `config`.
  func configureReader(config: ReaderConfig, shouldPersist: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  /// Configures Wi-Fi on the connected reader.
  ///
  /// The reader must be connected over USB before applying Wi-Fi settings.
  func configureWifi(config: WifiConfig, completion: @escaping (Result<Void, Error>) -> Void)
  /// Returns Wi-Fi status for the connected reader.
  func wifiStatus(completion: @escaping (Result<WifiStatus, Error>) -> Void)
  /// Disconnects a current reader.
  func disconnectReader(completion: @escaping (Result<Void, Error>) -> Void)
  /// Trigger device status
  func triggerDeviceStatus(completion: @escaping (Result<Void, Error>) -> Void)
  /// Start locating the specified `tags`.
  /// If `disableBeep` is true, the reader will not beep for tags not in the locate list.
  func startLocating(tags: [RfidTag], disableBeep: Bool?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Stop locating tags.
  func stopLocating(completion: @escaping (Result<Void, Error>) -> Void)
  /// Reset the locate state (clears session, allows new locate operations).
  func resetLocateState(completion: @escaping (Result<Void, Error>) -> Void)
  /// Reader currently in use
  func currentReader() throws -> Reader?
  /// Reader config
  func readerConfig(completion: @escaping (Result<ReaderConfig, Error>) -> Void)
  /// Supported regulatory regions for the current or last-selected reader.
  func supportedReaderRegions(completion: @escaping (Result<[ReaderRegion], Error>) -> Void)
  /// Applies a regulatory region to the current reader.
  func setReaderRegion(regionCode: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Runtime diagnostics snapshot (counters / last error / state)
  func diagnostics(completion: @escaping (Result<Diagnostics, Error>) -> Void)
  /// Enable or disable hardware-trigger initiated scanning/inventory.
  /// When disabled, trigger pulls are ignored and any active inventory is stopped.
  func setScanningEnabled(enabled: Bool, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterZebraRfidSetup {
  static var codec: FlutterStandardMessageCodec { FlutterZebraRfidPigeonCodec.shared }
  /// Sets up an instance of `FlutterZebraRfid` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterZebraRfid?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns list with names of available readers for specified `connectionType`.
    let updateAvailableReadersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.updateAvailableReaders\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateAvailableReadersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let connectionTypeArg = args[0] as! ReaderConnectionType
        api.updateAvailableReaders(connectionType: connectionTypeArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateAvailableReadersChannel.setMessageHandler(nil)
    }
    /// Starts Bluetooth classic device discovery for pairing.
    let startBluetoothScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.startBluetoothScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startBluetoothScanChannel.setMessageHandler { _, reply in
        api.startBluetoothScan { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startBluetoothScanChannel.setMessageHandler(nil)
    }
    /// Stops Bluetooth classic device discovery.
    let stopBluetoothScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.stopBluetoothScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopBluetoothScanChannel.setMessageHandler { _, reply in
        api.stopBluetoothScan { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopBluetoothScanChannel.setMessageHandler(nil)
    }
    /// Returns currently bonded Bluetooth devices.
    let getBondedDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.getBondedDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBondedDevicesChannel.setMessageHandler { _, reply in
        api.getBondedDevices { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBondedDevicesChannel.setMessageHandler(nil)
    }
    /// Starts pairing with the Bluetooth device at `address`.
    let pairBluetoothDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.pairBluetoothDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pairBluetoothDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        api.pairBluetoothDevice(address: addressArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pairBluetoothDeviceChannel.setMessageHandler(nil)
    }
    /// Connects to a reader with `readerId` ID.
    let connectReaderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.connectReader\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectReaderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let readerIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        api.connectReader(readerId: readerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectReaderChannel.setMessageHandler(nil)
    }
    /// Connects directly to a network reader by IP address or host name.
    let connectReaderByIpChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.connectReaderByIp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectReaderByIpChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let hostArg = args[0] as! String
        let portArg: Int64? = isNullish(args[1]) ? nil : (args[1] is Int64? ? args[1] as! Int64? : Int64(args[1] as! Int32))
        api.connectReaderByIp(host: hostArg, port: portArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectReaderByIpChannel.setMessageHandler(nil)
    }
    /// Configures reader with `config`.
    let configureReaderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.configureReader\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureReaderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ReaderConfig
        let shouldPersistArg = args[1] as! Bool
        api.configureReader(config: configArg, shouldPersist: shouldPersistArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureReaderChannel.setMessageHandler(nil)
    }
    /// Configures Wi-Fi on the connected reader.
    ///
    /// The reader must be connected over USB before applying Wi-Fi settings.
    let configureWifiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.configureWifi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureWifiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! WifiConfig
        api.configureWifi(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureWifiChannel.setMessageHandler(nil)
    }
    /// Returns Wi-Fi status for the connected reader.
    let wifiStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.wifiStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      wifiStatusChannel.setMessageHandler { _, reply in
        api.wifiStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      wifiStatusChannel.setMessageHandler(nil)
    }
    /// Disconnects a current reader.
    let disconnectReaderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.disconnectReader\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectReaderChannel.setMessageHandler { _, reply in
        api.disconnectReader { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectReaderChannel.setMessageHandler(nil)
    }
    /// Trigger device status
    let triggerDeviceStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.triggerDeviceStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      triggerDeviceStatusChannel.setMessageHandler { _, reply in
        api.triggerDeviceStatus { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      triggerDeviceStatusChannel.setMessageHandler(nil)
    }
    /// Start locating the specified `tags`.
    /// If `disableBeep` is true, the reader will not beep for tags not in the locate list.
    let startLocatingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.startLocating\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startLocatingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagsArg = args[0] as! [RfidTag]
        let disableBeepArg: Bool? = nilOrValue(args[1])
        api.startLocating(tags: tagsArg, disableBeep: disableBeepArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startLocatingChannel.setMessageHandler(nil)
    }
    /// Stop locating tags.
    let stopLocatingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.stopLocating\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopLocatingChannel.setMessageHandler { _, reply in
        api.stopLocating { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopLocatingChannel.setMessageHandler(nil)
    }
    /// Reset the locate state (clears session, allows new locate operations).
    let resetLocateStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.resetLocateState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetLocateStateChannel.setMessageHandler { _, reply in
        api.resetLocateState { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resetLocateStateChannel.setMessageHandler(nil)
    }
    /// Reader currently in use
    let currentReaderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.currentReader\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      currentReaderChannel.setMessageHandler { _, reply in
        do {
          let result = try api.currentReader()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      currentReaderChannel.setMessageHandler(nil)
    }
    /// Reader config
    let readerConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.readerConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readerConfigChannel.setMessageHandler { _, reply in
        api.readerConfig { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readerConfigChannel.setMessageHandler(nil)
    }
    /// Supported regulatory regions for the current or last-selected reader.
    let supportedReaderRegionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.supportedReaderRegions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      supportedReaderRegionsChannel.setMessageHandler { _, reply in
        api.supportedReaderRegions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      supportedReaderRegionsChannel.setMessageHandler(nil)
    }
    /// Applies a regulatory region to the current reader.
    let setReaderRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.setReaderRegion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setReaderRegionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let regionCodeArg = args[0] as! String
        api.setReaderRegion(regionCode: regionCodeArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setReaderRegionChannel.setMessageHandler(nil)
    }
    /// Runtime diagnostics snapshot (counters / last error / state)
    let diagnosticsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.diagnostics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      diagnosticsChannel.setMessageHandler { _, reply in
        api.diagnostics { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      diagnosticsChannel.setMessageHandler(nil)
    }
    /// Enable or disable hardware-trigger initiated scanning/inventory.
    /// When disabled, trigger pulls are ignored and any active inventory is stopped.
    let setScanningEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.setScanningEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setScanningEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        api.setScanningEnabled(enabled: enabledArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setScanningEnabledChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FlutterZebraRfidCallbacksProtocol {
  func onAvailableReadersChanged(readers readersArg: [Reader], completion: @escaping (Result<Void, FlutterRfidError>) -> Void)
  func onReaderConnectionStatusChanged(status statusArg: ReaderConnectionStatus, completion: @escaping (Result<Void, FlutterRfidError>) -> Void)
  func onTagsRead(tags tagsArg: [RfidTag], completion: @escaping (Result<Void, FlutterRfidError>) -> Void)
  func onBatteryDataReceived(batteryData batteryDataArg: BatteryData, completion: @escaping (Result<Void, FlutterRfidError>) -> Void)
  func onTagsLocated(tags tagsArg: [RfidTag], completion: @escaping (Result<Void, FlutterRfidError>) -> Void)
  func onBluetoothDeviceDiscovered(device deviceArg: BluetoothDevice, completion: @escaping (Result<Void, FlutterRfidError>) -> Void)
  func onBluetoothScanStatusChanged(status statusArg: BluetoothScanStatus, completion: @escaping (Result<Void, FlutterRfidError>) -> Void)
  func onBluetoothPairingResult(device deviceArg: BluetoothDevice, success successArg: Bool, completion: @escaping (Result<Void, FlutterRfidError>) -> Void)
  func onReaderConnectionError(error errorArg: ReaderError, completion: @escaping (Result<Void, FlutterRfidError>) -> Void)
}
class FlutterZebraRfidCallbacks: FlutterZebraRfidCallbacksProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FlutterZebraRfidPigeonCodec {
    return FlutterZebraRfidPigeonCodec.shared
  }
  func onAvailableReadersChanged(readers readersArg: [Reader], completion: @escaping (Result<Void, FlutterRfidError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onAvailableReadersChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([readersArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterRfidError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onReaderConnectionStatusChanged(status statusArg: ReaderConnectionStatus, completion: @escaping (Result<Void, FlutterRfidError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onReaderConnectionStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterRfidError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onTagsRead(tags tagsArg: [RfidTag], completion: @escaping (Result<Void, FlutterRfidError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onTagsRead\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tagsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterRfidError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBatteryDataReceived(batteryData batteryDataArg: BatteryData, completion: @escaping (Result<Void, FlutterRfidError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onBatteryDataReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([batteryDataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterRfidError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onTagsLocated(tags tagsArg: [RfidTag], completion: @escaping (Result<Void, FlutterRfidError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onTagsLocated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tagsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterRfidError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBluetoothDeviceDiscovered(device deviceArg: BluetoothDevice, completion: @escaping (Result<Void, FlutterRfidError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onBluetoothDeviceDiscovered\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterRfidError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBluetoothScanStatusChanged(status statusArg: BluetoothScanStatus, completion: @escaping (Result<Void, FlutterRfidError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onBluetoothScanStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterRfidError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBluetoothPairingResult(device deviceArg: BluetoothDevice, success successArg: Bool, completion: @escaping (Result<Void, FlutterRfidError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onBluetoothPairingResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg, successArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterRfidError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onReaderConnectionError(error errorArg: ReaderError, completion: @escaping (Result<Void, FlutterRfidError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onReaderConnectionError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterRfidError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
