// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterCaptureError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterCaptureError {
  return FlutterCaptureError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterCaptureError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class CaptureDeviceStatus(val raw: Int) {
  CONNECTING(0),
  CONNECTED(1),
  DEGRADED(2),
  DISCONNECTING(3),
  DISCONNECTED(4),
  ERROR(5);

  companion object {
    fun ofRaw(raw: Int): CaptureDeviceStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CaptureCapabilityStatus(val raw: Int) {
  UNAVAILABLE(0),
  DISCONNECTED(1),
  CONNECTING(2),
  CONNECTED(3),
  ERROR(4);

  companion object {
    fun ofRaw(raw: Int): CaptureCapabilityStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CaptureCapabilityType(val raw: Int) {
  RFID(0),
  BARCODE(1);

  companion object {
    fun ofRaw(raw: Int): CaptureCapabilityType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CaptureDeviceTopology(val raw: Int) {
  BLUETOOTH_COMBO_READER(0),
  TC22RFID_SLED(1),
  EXTERNAL_RFID_WITH_TERMINAL_BARCODE(2),
  RFID_ONLY(3),
  BARCODE_ONLY(4),
  UNKNOWN(5);

  companion object {
    fun ofRaw(raw: Int): CaptureDeviceTopology? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CaptureMatchConfidence(val raw: Int) {
  EXACT(0),
  HIGH(1),
  MEDIUM(2),
  LOW(3),
  MANUAL(4);

  companion object {
    fun ofRaw(raw: Int): CaptureMatchConfidence? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CaptureBarcodeSource(val raw: Int) {
  BUILT_IN_TERMINAL(0),
  RFID_SLED(1),
  EXTERNAL_BLUETOOTH(2),
  EXTERNAL_USB(3),
  UNKNOWN(4);

  companion object {
    fun ofRaw(raw: Int): CaptureBarcodeSource? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CaptureBarcodeMode(val raw: Int) {
  AUTO(0),
  DATA_WEDGE(1),
  SCANNER_SDK(2);

  companion object {
    fun ofRaw(raw: Int): CaptureBarcodeMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CaptureReaderConfigBatchMode(val raw: Int) {
  AUTO(0),
  ENABLED(1),
  DISABLED(2);

  companion object {
    fun ofRaw(raw: Int): CaptureReaderConfigBatchMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CaptureReaderBeeperVolume(val raw: Int) {
  QUIET(0),
  LOW(1),
  MEDIUM(2),
  HIGH(3);

  companion object {
    fun ofRaw(raw: Int): CaptureReaderBeeperVolume? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CaptureReaderConfig (
  val transmitPowerIndex: Long? = null,
  val tari: Long? = null,
  val beeperVolume: CaptureReaderBeeperVolume? = null,
  val enableDynamicPower: Boolean? = null,
  val enableLedBlink: Boolean? = null,
  val batchMode: CaptureReaderConfigBatchMode? = null,
  val scanBatchMode: CaptureReaderConfigBatchMode? = null,
  val rfModeTableIndex: Long? = null,
  val receiveSensitivityIndex: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CaptureReaderConfig {
      val transmitPowerIndex = pigeonVar_list[0].let { num -> if (num is Int) num.toLong() else num as Long? }
      val tari = pigeonVar_list[1].let { num -> if (num is Int) num.toLong() else num as Long? }
      val beeperVolume = pigeonVar_list[2] as CaptureReaderBeeperVolume?
      val enableDynamicPower = pigeonVar_list[3] as Boolean?
      val enableLedBlink = pigeonVar_list[4] as Boolean?
      val batchMode = pigeonVar_list[5] as CaptureReaderConfigBatchMode?
      val scanBatchMode = pigeonVar_list[6] as CaptureReaderConfigBatchMode?
      val rfModeTableIndex = pigeonVar_list[7].let { num -> if (num is Int) num.toLong() else num as Long? }
      val receiveSensitivityIndex = pigeonVar_list[8].let { num -> if (num is Int) num.toLong() else num as Long? }
      return CaptureReaderConfig(transmitPowerIndex, tari, beeperVolume, enableDynamicPower, enableLedBlink, batchMode, scanBatchMode, rfModeTableIndex, receiveSensitivityIndex)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      transmitPowerIndex,
      tari,
      beeperVolume,
      enableDynamicPower,
      enableLedBlink,
      batchMode,
      scanBatchMode,
      rfModeTableIndex,
      receiveSensitivityIndex,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CaptureRfidCapability (
  val readerId: Long,
  val hardwareIdentity: String,
  val displayName: String,
  val status: CaptureCapabilityStatus,
  val model: String? = null,
  val serialNumber: String? = null,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CaptureRfidCapability {
      val readerId = pigeonVar_list[0].let { num -> if (num is Int) num.toLong() else num as Long }
      val hardwareIdentity = pigeonVar_list[1] as String
      val displayName = pigeonVar_list[2] as String
      val status = pigeonVar_list[3] as CaptureCapabilityStatus
      val model = pigeonVar_list[4] as String?
      val serialNumber = pigeonVar_list[5] as String?
      val error = pigeonVar_list[6] as String?
      return CaptureRfidCapability(readerId, hardwareIdentity, displayName, status, model, serialNumber, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      readerId,
      hardwareIdentity,
      displayName,
      status,
      model,
      serialNumber,
      error,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CaptureBarcodeCapability (
  val endpointId: String,
  val displayName: String,
  val source: CaptureBarcodeSource,
  val mode: CaptureBarcodeMode,
  val status: CaptureCapabilityStatus,
  val preferred: Boolean,
  val scannerId: Long? = null,
  val model: String? = null,
  val serialNumber: String? = null,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CaptureBarcodeCapability {
      val endpointId = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val source = pigeonVar_list[2] as CaptureBarcodeSource
      val mode = pigeonVar_list[3] as CaptureBarcodeMode
      val status = pigeonVar_list[4] as CaptureCapabilityStatus
      val preferred = pigeonVar_list[5] as Boolean
      val scannerId = pigeonVar_list[6].let { num -> if (num is Int) num.toLong() else num as Long? }
      val model = pigeonVar_list[7] as String?
      val serialNumber = pigeonVar_list[8] as String?
      val error = pigeonVar_list[9] as String?
      return CaptureBarcodeCapability(endpointId, displayName, source, mode, status, preferred, scannerId, model, serialNumber, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      endpointId,
      displayName,
      source,
      mode,
      status,
      preferred,
      scannerId,
      model,
      serialNumber,
      error,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CaptureDevice (
  val id: String,
  val displayName: String,
  val topology: CaptureDeviceTopology,
  val status: CaptureDeviceStatus,
  val matchConfidence: CaptureMatchConfidence,
  val matchReason: String,
  val active: Boolean,
  val rfid: CaptureRfidCapability? = null,
  val barcode: CaptureBarcodeCapability? = null,
  val lastError: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CaptureDevice {
      val id = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val topology = pigeonVar_list[2] as CaptureDeviceTopology
      val status = pigeonVar_list[3] as CaptureDeviceStatus
      val matchConfidence = pigeonVar_list[4] as CaptureMatchConfidence
      val matchReason = pigeonVar_list[5] as String
      val active = pigeonVar_list[6] as Boolean
      val rfid = pigeonVar_list[7] as CaptureRfidCapability?
      val barcode = pigeonVar_list[8] as CaptureBarcodeCapability?
      val lastError = pigeonVar_list[9] as String?
      return CaptureDevice(id, displayName, topology, status, matchConfidence, matchReason, active, rfid, barcode, lastError)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      displayName,
      topology,
      status,
      matchConfidence,
      matchReason,
      active,
      rfid,
      barcode,
      lastError,
    )
  }
}
private object FlutterZebraCapturePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          CaptureDeviceStatus.ofRaw(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          CaptureCapabilityStatus.ofRaw(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          CaptureCapabilityType.ofRaw(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          CaptureDeviceTopology.ofRaw(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          CaptureMatchConfidence.ofRaw(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          CaptureBarcodeSource.ofRaw(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          CaptureBarcodeMode.ofRaw(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          CaptureReaderConfigBatchMode.ofRaw(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          CaptureReaderBeeperVolume.ofRaw(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CaptureReaderConfig.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CaptureRfidCapability.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CaptureBarcodeCapability.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CaptureDevice.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CaptureDeviceStatus -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is CaptureCapabilityStatus -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is CaptureCapabilityType -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is CaptureDeviceTopology -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is CaptureMatchConfidence -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is CaptureBarcodeSource -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is CaptureBarcodeMode -> {
        stream.write(135)
        writeValue(stream, value.raw)
      }
      is CaptureReaderConfigBatchMode -> {
        stream.write(136)
        writeValue(stream, value.raw)
      }
      is CaptureReaderBeeperVolume -> {
        stream.write(137)
        writeValue(stream, value.raw)
      }
      is CaptureReaderConfig -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is CaptureRfidCapability -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is CaptureBarcodeCapability -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is CaptureDevice -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FlutterZebraCapture {
  fun refreshCaptureDevices(callback: (Result<Unit>) -> Unit)
  fun connectCaptureDevice(captureDeviceId: String, rfidConfig: CaptureReaderConfig?, callback: (Result<Unit>) -> Unit)
  fun disconnectCaptureDevice(captureDeviceId: String, callback: (Result<Unit>) -> Unit)
  fun setCaptureDeviceBarcodeOverride(captureDeviceId: String, barcodeEndpointId: String, callback: (Result<Unit>) -> Unit)
  fun configureCaptureDevice(captureDeviceId: String, rfidConfig: CaptureReaderConfig, shouldPersist: Boolean, callback: (Result<Unit>) -> Unit)
  fun setCaptureDeviceForeground(foreground: Boolean, callback: (Result<Unit>) -> Unit)
  fun activeCaptureDevice(): CaptureDevice?

  companion object {
    /** The codec used by FlutterZebraCapture. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterZebraCapturePigeonCodec
    }
    /** Sets up an instance of `FlutterZebraCapture` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterZebraCapture?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.refreshCaptureDevices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.refreshCaptureDevices{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.connectCaptureDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val captureDeviceIdArg = args[0] as String
            val rfidConfigArg = args[1] as CaptureReaderConfig?
            api.connectCaptureDevice(captureDeviceIdArg, rfidConfigArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.disconnectCaptureDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val captureDeviceIdArg = args[0] as String
            api.disconnectCaptureDevice(captureDeviceIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.setCaptureDeviceBarcodeOverride$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val captureDeviceIdArg = args[0] as String
            val barcodeEndpointIdArg = args[1] as String
            api.setCaptureDeviceBarcodeOverride(captureDeviceIdArg, barcodeEndpointIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.configureCaptureDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val captureDeviceIdArg = args[0] as String
            val rfidConfigArg = args[1] as CaptureReaderConfig
            val shouldPersistArg = args[2] as Boolean
            api.configureCaptureDevice(captureDeviceIdArg, rfidConfigArg, shouldPersistArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.setCaptureDeviceForeground$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val foregroundArg = args[0] as Boolean
            api.setCaptureDeviceForeground(foregroundArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.activeCaptureDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.activeCaptureDevice())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class FlutterZebraCaptureCallbacks(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FlutterZebraCaptureCallbacks. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterZebraCapturePigeonCodec
    }
  }
  fun onAvailableCaptureDevicesChanged(devicesArg: List<CaptureDevice>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onAvailableCaptureDevicesChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(devicesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterCaptureError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      }
    }
  }
  fun onActiveCaptureDeviceChanged(deviceArg: CaptureDevice?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onActiveCaptureDeviceChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterCaptureError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      }
    }
  }
  fun onCaptureDeviceStatusChanged(deviceArg: CaptureDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onCaptureDeviceStatusChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterCaptureError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      }
    }
  }
}
