// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterRfidError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterRfidError {
  return FlutterRfidError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterRfidError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ReaderConnectionType(val raw: Int) {
  BLUETOOTH(0),
  USB(1),
  ALL(2);

  companion object {
    fun ofRaw(raw: Int): ReaderConnectionType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ReaderConnectionStatus(val raw: Int) {
  CONNECTING(0),
  CONNECTED(1),
  DISCONNECTING(2),
  DISCONNECTED(3),
  ERROR(4);

  companion object {
    fun ofRaw(raw: Int): ReaderConnectionStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ReaderConfigBatchMode(val raw: Int) {
  AUTO(0),
  ENABLED(1),
  DISABLED(2);

  companion object {
    fun ofRaw(raw: Int): ReaderConfigBatchMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ReaderBeeperVolume(val raw: Int) {
  QUIET(0),
  LOW(1),
  MEDIUM(2),
  HIGH(3);

  companion object {
    fun ofRaw(raw: Int): ReaderBeeperVolume? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Reader (
  val name: String? = null,
  val id: Long,
  val info: ReaderInfo? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Reader {
      val name = pigeonVar_list[0] as String?
      val id = pigeonVar_list[1].let { num -> if (num is Int) num.toLong() else num as Long }
      val info = pigeonVar_list[2] as ReaderInfo?
      return Reader(name, id, info)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      id,
      info,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReaderConfig (
  val transmitPowerIndex: Long? = null,
  val beeperVolume: ReaderBeeperVolume? = null,
  val enableDynamicPower: Boolean? = null,
  val enableLedBlink: Boolean? = null,
  val batchMode: ReaderConfigBatchMode? = null,
  val scanBatchMode: ReaderConfigBatchMode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReaderConfig {
      val transmitPowerIndex = pigeonVar_list[0].let { num -> if (num is Int) num.toLong() else num as Long? }
      val beeperVolume = pigeonVar_list[1] as ReaderBeeperVolume?
      val enableDynamicPower = pigeonVar_list[2] as Boolean?
      val enableLedBlink = pigeonVar_list[3] as Boolean?
      val batchMode = pigeonVar_list[4] as ReaderConfigBatchMode?
      val scanBatchMode = pigeonVar_list[5] as ReaderConfigBatchMode?
      return ReaderConfig(transmitPowerIndex, beeperVolume, enableDynamicPower, enableLedBlink, batchMode, scanBatchMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      transmitPowerIndex,
      beeperVolume,
      enableDynamicPower,
      enableLedBlink,
      batchMode,
      scanBatchMode,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReaderInfo (
  val transmitPowerLevels: List<Any?>,
  val firmwareVersion: String,
  val modelVersion: String,
  val scannerName: String,
  val serialNumber: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReaderInfo {
      val transmitPowerLevels = pigeonVar_list[0] as List<Any?>
      val firmwareVersion = pigeonVar_list[1] as String
      val modelVersion = pigeonVar_list[2] as String
      val scannerName = pigeonVar_list[3] as String
      val serialNumber = pigeonVar_list[4] as String
      return ReaderInfo(transmitPowerLevels, firmwareVersion, modelVersion, scannerName, serialNumber)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      transmitPowerLevels,
      firmwareVersion,
      modelVersion,
      scannerName,
      serialNumber,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RfidTag (
  val id: String,
  val rssi: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RfidTag {
      val id = pigeonVar_list[0] as String
      val rssi = pigeonVar_list[1].let { num -> if (num is Int) num.toLong() else num as Long }
      return RfidTag(id, rssi)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      rssi,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BatteryData (
  val level: Long,
  val isCharging: Boolean,
  val cause: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BatteryData {
      val level = pigeonVar_list[0].let { num -> if (num is Int) num.toLong() else num as Long }
      val isCharging = pigeonVar_list[1] as Boolean
      val cause = pigeonVar_list[2] as String
      return BatteryData(level, isCharging, cause)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      level,
      isCharging,
      cause,
    )
  }
}
private object FlutterZebraRfidPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          ReaderConnectionType.ofRaw(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          ReaderConnectionStatus.ofRaw(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          ReaderConfigBatchMode.ofRaw(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Int?)?.let {
          ReaderBeeperVolume.ofRaw(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Reader.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReaderConfig.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReaderInfo.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RfidTag.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BatteryData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ReaderConnectionType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is ReaderConnectionStatus -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is ReaderConfigBatchMode -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is ReaderBeeperVolume -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is Reader -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ReaderConfig -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ReaderInfo -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is RfidTag -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is BatteryData -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FlutterZebraRfid {
  /** Returns list with names of available readers for specified `connectionType`. */
  fun updateAvailableReaders(connectionType: ReaderConnectionType, callback: (Result<Unit>) -> Unit)
  /** Connects to a reader with `readerId` ID. */
  fun connectReader(readerId: Long, callback: (Result<Unit>) -> Unit)
  /** Configures reader with `config`. */
  fun configureReader(config: ReaderConfig, shouldPersist: Boolean, callback: (Result<Unit>) -> Unit)
  /** Disconnects a reader with `readerName` name. */
  fun disconnectReader(callback: (Result<Unit>) -> Unit)
  /** Trigger device status */
  fun triggerDeviceStatus(callback: (Result<Unit>) -> Unit)
  /** Reader currently in use */
  fun currentReader(): Reader?

  companion object {
    /** The codec used by FlutterZebraRfid. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterZebraRfidPigeonCodec
    }
    /** Sets up an instance of `FlutterZebraRfid` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterZebraRfid?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.updateAvailableReaders$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val connectionTypeArg = args[0] as ReaderConnectionType
            api.updateAvailableReaders(connectionTypeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.connectReader$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val readerIdArg = args[0].let { num -> if (num is Int) num.toLong() else num as Long }
            api.connectReader(readerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.configureReader$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as ReaderConfig
            val shouldPersistArg = args[1] as Boolean
            api.configureReader(configArg, shouldPersistArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.disconnectReader$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.disconnectReader{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.triggerDeviceStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.triggerDeviceStatus{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfid.currentReader$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.currentReader())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class FlutterZebraRfidCallbacks(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FlutterZebraRfidCallbacks. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterZebraRfidPigeonCodec
    }
  }
  fun onAvailableReadersChanged(readersArg: List<Reader>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onAvailableReadersChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(readersArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterRfidError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onReaderConnectionStatusChanged(statusArg: ReaderConnectionStatus, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onReaderConnectionStatusChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterRfidError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onTagsRead(tagsArg: List<RfidTag>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onTagsRead$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(tagsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterRfidError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onBatteryDataReceived(batteryDataArg: BatteryData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_zebra_rfid.FlutterZebraRfidCallbacks.onBatteryDataReceived$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(batteryDataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterRfidError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
