// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse(
    {Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum CaptureDeviceStatus {
  connecting,
  connected,
  degraded,
  disconnecting,
  disconnected,
  error,
}

enum CaptureCapabilityStatus {
  unavailable,
  disconnected,
  connecting,
  connected,
  error,
}

enum CaptureCapabilityType {
  rfid,
  barcode,
}

enum CaptureDeviceTopology {
  bluetoothComboReader,
  tc22RfidSled,
  externalRfidWithTerminalBarcode,
  rfidOnly,
  barcodeOnly,
  unknown,
}

enum CaptureMatchConfidence {
  exact,
  high,
  medium,
  low,
  manual,
}

enum CaptureBarcodeSource {
  builtInTerminal,
  rfidSled,
  externalBluetooth,
  externalUsb,
  unknown,
}

enum CaptureBarcodeMode {
  auto,
  dataWedge,
  scannerSdk,
}

enum CaptureReaderConfigBatchMode {
  auto,
  enabled,
  disabled,
}

enum CaptureReaderBeeperVolume {
  quiet,
  low,
  medium,
  high,
}

class CaptureReaderConfig {
  CaptureReaderConfig({
    this.transmitPowerIndex,
    this.tari,
    this.beeperVolume,
    this.enableDynamicPower,
    this.enableLedBlink,
    this.batchMode,
    this.scanBatchMode,
    this.rfModeTableIndex,
    this.receiveSensitivityIndex,
  });

  int? transmitPowerIndex;

  int? tari;

  CaptureReaderBeeperVolume? beeperVolume;

  bool? enableDynamicPower;

  bool? enableLedBlink;

  CaptureReaderConfigBatchMode? batchMode;

  CaptureReaderConfigBatchMode? scanBatchMode;

  int? rfModeTableIndex;

  int? receiveSensitivityIndex;

  Object encode() {
    return <Object?>[
      transmitPowerIndex,
      tari,
      beeperVolume,
      enableDynamicPower,
      enableLedBlink,
      batchMode,
      scanBatchMode,
      rfModeTableIndex,
      receiveSensitivityIndex,
    ];
  }

  static CaptureReaderConfig decode(Object result) {
    result as List<Object?>;
    return CaptureReaderConfig(
      transmitPowerIndex: result[0] as int?,
      tari: result[1] as int?,
      beeperVolume: result[2] as CaptureReaderBeeperVolume?,
      enableDynamicPower: result[3] as bool?,
      enableLedBlink: result[4] as bool?,
      batchMode: result[5] as CaptureReaderConfigBatchMode?,
      scanBatchMode: result[6] as CaptureReaderConfigBatchMode?,
      rfModeTableIndex: result[7] as int?,
      receiveSensitivityIndex: result[8] as int?,
    );
  }
}

class CaptureRfidCapability {
  CaptureRfidCapability({
    required this.readerId,
    required this.hardwareIdentity,
    required this.displayName,
    required this.status,
    this.model,
    this.serialNumber,
    this.error,
  });

  int readerId;

  String hardwareIdentity;

  String displayName;

  CaptureCapabilityStatus status;

  String? model;

  String? serialNumber;

  String? error;

  Object encode() {
    return <Object?>[
      readerId,
      hardwareIdentity,
      displayName,
      status,
      model,
      serialNumber,
      error,
    ];
  }

  static CaptureRfidCapability decode(Object result) {
    result as List<Object?>;
    return CaptureRfidCapability(
      readerId: result[0]! as int,
      hardwareIdentity: result[1]! as String,
      displayName: result[2]! as String,
      status: result[3]! as CaptureCapabilityStatus,
      model: result[4] as String?,
      serialNumber: result[5] as String?,
      error: result[6] as String?,
    );
  }
}

class CaptureBarcodeCapability {
  CaptureBarcodeCapability({
    required this.endpointId,
    required this.displayName,
    required this.source,
    required this.mode,
    required this.status,
    required this.preferred,
    this.scannerId,
    this.model,
    this.serialNumber,
    this.error,
  });

  String endpointId;

  String displayName;

  CaptureBarcodeSource source;

  CaptureBarcodeMode mode;

  CaptureCapabilityStatus status;

  bool preferred;

  int? scannerId;

  String? model;

  String? serialNumber;

  String? error;

  Object encode() {
    return <Object?>[
      endpointId,
      displayName,
      source,
      mode,
      status,
      preferred,
      scannerId,
      model,
      serialNumber,
      error,
    ];
  }

  static CaptureBarcodeCapability decode(Object result) {
    result as List<Object?>;
    return CaptureBarcodeCapability(
      endpointId: result[0]! as String,
      displayName: result[1]! as String,
      source: result[2]! as CaptureBarcodeSource,
      mode: result[3]! as CaptureBarcodeMode,
      status: result[4]! as CaptureCapabilityStatus,
      preferred: result[5]! as bool,
      scannerId: result[6] as int?,
      model: result[7] as String?,
      serialNumber: result[8] as String?,
      error: result[9] as String?,
    );
  }
}

class CaptureDevice {
  CaptureDevice({
    required this.id,
    required this.displayName,
    required this.topology,
    required this.status,
    required this.matchConfidence,
    required this.matchReason,
    required this.active,
    this.rfid,
    this.barcode,
    this.lastError,
  });

  String id;

  String displayName;

  CaptureDeviceTopology topology;

  CaptureDeviceStatus status;

  CaptureMatchConfidence matchConfidence;

  String matchReason;

  bool active;

  CaptureRfidCapability? rfid;

  CaptureBarcodeCapability? barcode;

  String? lastError;

  Object encode() {
    return <Object?>[
      id,
      displayName,
      topology,
      status,
      matchConfidence,
      matchReason,
      active,
      rfid,
      barcode,
      lastError,
    ];
  }

  static CaptureDevice decode(Object result) {
    result as List<Object?>;
    return CaptureDevice(
      id: result[0]! as String,
      displayName: result[1]! as String,
      topology: result[2]! as CaptureDeviceTopology,
      status: result[3]! as CaptureDeviceStatus,
      matchConfidence: result[4]! as CaptureMatchConfidence,
      matchReason: result[5]! as String,
      active: result[6]! as bool,
      rfid: result[7] as CaptureRfidCapability?,
      barcode: result[8] as CaptureBarcodeCapability?,
      lastError: result[9] as String?,
    );
  }
}

class CaptureDiagnosticEvent {
  CaptureDiagnosticEvent({
    required this.timestampMs,
    required this.sequence,
    required this.category,
    required this.operation,
    required this.outcome,
    required this.detailsJson,
  });

  int timestampMs;

  int sequence;

  String category;

  String operation;

  String outcome;

  String detailsJson;

  Object encode() {
    return <Object?>[
      timestampMs,
      sequence,
      category,
      operation,
      outcome,
      detailsJson,
    ];
  }

  static CaptureDiagnosticEvent decode(Object result) {
    result as List<Object?>;
    return CaptureDiagnosticEvent(
      timestampMs: result[0]! as int,
      sequence: result[1]! as int,
      category: result[2]! as String,
      operation: result[3]! as String,
      outcome: result[4]! as String,
      detailsJson: result[5]! as String,
    );
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is CaptureDeviceStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CaptureCapabilityStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is CaptureCapabilityType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is CaptureDeviceTopology) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is CaptureMatchConfidence) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is CaptureBarcodeSource) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is CaptureBarcodeMode) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is CaptureReaderConfigBatchMode) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is CaptureReaderBeeperVolume) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is CaptureReaderConfig) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is CaptureRfidCapability) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is CaptureBarcodeCapability) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is CaptureDevice) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is CaptureDiagnosticEvent) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CaptureDeviceStatus.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CaptureCapabilityStatus.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CaptureCapabilityType.values[value];
      case 132:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CaptureDeviceTopology.values[value];
      case 133:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CaptureMatchConfidence.values[value];
      case 134:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CaptureBarcodeSource.values[value];
      case 135:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CaptureBarcodeMode.values[value];
      case 136:
        final int? value = readValue(buffer) as int?;
        return value == null
            ? null
            : CaptureReaderConfigBatchMode.values[value];
      case 137:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CaptureReaderBeeperVolume.values[value];
      case 138:
        return CaptureReaderConfig.decode(readValue(buffer)!);
      case 139:
        return CaptureRfidCapability.decode(readValue(buffer)!);
      case 140:
        return CaptureBarcodeCapability.decode(readValue(buffer)!);
      case 141:
        return CaptureDevice.decode(readValue(buffer)!);
      case 142:
        return CaptureDiagnosticEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FlutterZebraCapture {
  /// Constructor for [FlutterZebraCapture].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterZebraCapture(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> refreshCaptureDevices() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.refreshCaptureDevices$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> connectCaptureDevice(
      String captureDeviceId, CaptureReaderConfig? rfidConfig) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.connectCaptureDevice$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[captureDeviceId, rfidConfig]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disconnectCaptureDevice(String captureDeviceId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.disconnectCaptureDevice$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[captureDeviceId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setCaptureDeviceBarcodeOverride(
      String captureDeviceId, String barcodeEndpointId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.setCaptureDeviceBarcodeOverride$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[captureDeviceId, barcodeEndpointId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> configureCaptureDevice(String captureDeviceId,
      CaptureReaderConfig rfidConfig, bool shouldPersist) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.configureCaptureDevice$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
            .send(<Object?>[captureDeviceId, rfidConfig, shouldPersist])
        as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setCaptureDeviceForeground(bool foreground) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.setCaptureDeviceForeground$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[foreground]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<CaptureDiagnosticEvent?>> captureDiagnostics() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.captureDiagnostics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!
          .cast<CaptureDiagnosticEvent?>();
    }
  }

  Future<void> clearCaptureDiagnostics() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.clearCaptureDiagnostics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<CaptureDevice?> activeCaptureDevice() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCapture.activeCaptureDevice$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as CaptureDevice?);
    }
  }
}

abstract class FlutterZebraCaptureCallbacks {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAvailableCaptureDevicesChanged(List<CaptureDevice?> devices);

  void onActiveCaptureDeviceChanged(CaptureDevice? device);

  void onCaptureDeviceStatusChanged(CaptureDevice device);

  static void setUp(
    FlutterZebraCaptureCallbacks? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<
          Object?> pigeonVar_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onAvailableCaptureDevicesChanged$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onAvailableCaptureDevicesChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<CaptureDevice?>? arg_devices =
              (args[0] as List<Object?>?)?.cast<CaptureDevice?>();
          assert(arg_devices != null,
              'Argument for dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onAvailableCaptureDevicesChanged was null, expected non-null List<CaptureDevice?>.');
          try {
            api.onAvailableCaptureDevicesChanged(arg_devices!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<
          Object?> pigeonVar_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onActiveCaptureDeviceChanged$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onActiveCaptureDeviceChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CaptureDevice? arg_device = (args[0] as CaptureDevice?);
          try {
            api.onActiveCaptureDeviceChanged(arg_device);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<
          Object?> pigeonVar_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onCaptureDeviceStatusChanged$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onCaptureDeviceStatusChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CaptureDevice? arg_device = (args[0] as CaptureDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.flutter_zebra_capture.FlutterZebraCaptureCallbacks.onCaptureDeviceStatusChanged was null, expected non-null CaptureDevice.');
          try {
            api.onCaptureDeviceStatusChanged(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
