// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum ScannerConnectionType {
  bluetooth,
  usb,
}

enum ScannerConnectionStatus {
  connecting,
  connected,
  disconnecting,
  disconnected,
  error,
}

enum BarcodeScannerSource {
  builtInTerminal,
  rfidSled,
  externalBluetooth,
  externalUsb,
  unknown,
}

enum BarcodeScannerMode {
  auto,
  dataWedge,
  scannerSdk,
}

class BarcodeScanner {
  BarcodeScanner({
    this.name,
    required this.id,
    this.model,
    this.serialNumber,
  });

  String? name;

  int id;

  String? model;

  String? serialNumber;

  Object encode() {
    return <Object?>[
      name,
      id,
      model,
      serialNumber,
    ];
  }

  static BarcodeScanner decode(Object result) {
    result as List<Object?>;
    return BarcodeScanner(
      name: result[0] as String?,
      id: result[1]! as int,
      model: result[2] as String?,
      serialNumber: result[3] as String?,
    );
  }
}

class Barcode {
  Barcode({
    required this.data,
    required this.scannerId,
    this.barcodeType,
    this.endpointId,
    this.source,
    this.scannerName,
  });

  String data;

  int scannerId;

  int? barcodeType;

  String? endpointId;

  BarcodeScannerSource? source;

  String? scannerName;

  Object encode() {
    return <Object?>[
      data,
      scannerId,
      barcodeType,
      endpointId,
      source,
      scannerName,
    ];
  }

  static Barcode decode(Object result) {
    result as List<Object?>;
    return Barcode(
      data: result[0]! as String,
      scannerId: result[1]! as int,
      barcodeType: result[2] as int?,
      endpointId: result[3] as String?,
      source: result[4] as BarcodeScannerSource?,
      scannerName: result[5] as String?,
    );
  }
}

class BarcodeScannerEndpoint {
  BarcodeScannerEndpoint({
    required this.endpointId,
    required this.displayName,
    required this.source,
    required this.mode,
    required this.connectionStatus,
    required this.active,
    required this.preferred,
    this.zebraScannerIdentifier,
    this.scannerIndex,
    this.scannerId,
    this.model,
    this.serialNumber,
  });

  String endpointId;

  String displayName;

  BarcodeScannerSource source;

  BarcodeScannerMode mode;

  ScannerConnectionStatus connectionStatus;

  bool active;

  bool preferred;

  String? zebraScannerIdentifier;

  int? scannerIndex;

  int? scannerId;

  String? model;

  String? serialNumber;

  Object encode() {
    return <Object?>[
      endpointId,
      displayName,
      source,
      mode,
      connectionStatus,
      active,
      preferred,
      zebraScannerIdentifier,
      scannerIndex,
      scannerId,
      model,
      serialNumber,
    ];
  }

  static BarcodeScannerEndpoint decode(Object result) {
    result as List<Object?>;
    return BarcodeScannerEndpoint(
      endpointId: result[0]! as String,
      displayName: result[1]! as String,
      source: result[2]! as BarcodeScannerSource,
      mode: result[3]! as BarcodeScannerMode,
      connectionStatus: result[4]! as ScannerConnectionStatus,
      active: result[5]! as bool,
      preferred: result[6]! as bool,
      zebraScannerIdentifier: result[7] as String?,
      scannerIndex: result[8] as int?,
      scannerId: result[9] as int?,
      model: result[10] as String?,
      serialNumber: result[11] as String?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is ScannerConnectionType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else     if (value is ScannerConnectionStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else     if (value is BarcodeScannerSource) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else     if (value is BarcodeScannerMode) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else     if (value is BarcodeScanner) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else     if (value is Barcode) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else     if (value is BarcodeScannerEndpoint) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ScannerConnectionType.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ScannerConnectionStatus.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : BarcodeScannerSource.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : BarcodeScannerMode.values[value];
      case 133: 
        return BarcodeScanner.decode(readValue(buffer)!);
      case 134: 
        return Barcode.decode(readValue(buffer)!);
      case 135: 
        return BarcodeScannerEndpoint.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FlutterZebraBarcode {
  /// Constructor for [FlutterZebraBarcode].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterZebraBarcode({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Returns list with names of available readers for specified `connectionType`.
  Future<void> updateAvailableScanners() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.updateAvailableScanners$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Connects to a reader with `readerId` ID.
  Future<void> connectScanner(int scannerId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.connectScanner$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[scannerId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Disconnects a current scanner.
  Future<void> disconnectScanner() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.disconnectScanner$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Refreshes all barcode scanner endpoints, including DataWedge-managed
  /// terminal scanners and Scanner SDK external scanners where available.
  Future<void> refreshBarcodeScanners() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.refreshBarcodeScanners$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Selects the endpoint that should be treated as the active barcode source.
  Future<void> setActiveBarcodeScanner(String endpointId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.setActiveBarcodeScanner$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[endpointId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Clears the explicit active barcode source.
  Future<void> clearActiveBarcodeScanner() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.clearActiveBarcodeScanner$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Reader currently in use
  Future<BarcodeScanner?> currentScanner() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.currentScanner$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as BarcodeScanner?);
    }
  }

  /// Barcode scanner endpoint currently selected, if any.
  Future<BarcodeScannerEndpoint?> activeBarcodeScanner() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcode.activeBarcodeScanner$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as BarcodeScannerEndpoint?);
    }
  }
}

abstract class FlutterZebraBarcodeCallbacks {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAvailableScannersChanged(List<BarcodeScanner?> readers);

  void onAvailableBarcodeScannersChanged(List<BarcodeScannerEndpoint?> endpoints);

  void onActiveBarcodeScannerChanged(BarcodeScannerEndpoint? endpoint);

  void onScannerConnectionStatusChanged(ScannerConnectionStatus status);

  void onBarcodeRead(Barcode barcode);

  static void setUp(FlutterZebraBarcodeCallbacks? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onAvailableScannersChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onAvailableScannersChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<BarcodeScanner?>? arg_readers = (args[0] as List<Object?>?)?.cast<BarcodeScanner?>();
          assert(arg_readers != null,
              'Argument for dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onAvailableScannersChanged was null, expected non-null List<BarcodeScanner?>.');
          try {
            api.onAvailableScannersChanged(arg_readers!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onAvailableBarcodeScannersChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onAvailableBarcodeScannersChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<BarcodeScannerEndpoint?>? arg_endpoints = (args[0] as List<Object?>?)?.cast<BarcodeScannerEndpoint?>();
          assert(arg_endpoints != null,
              'Argument for dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onAvailableBarcodeScannersChanged was null, expected non-null List<BarcodeScannerEndpoint?>.');
          try {
            api.onAvailableBarcodeScannersChanged(arg_endpoints!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onActiveBarcodeScannerChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onActiveBarcodeScannerChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BarcodeScannerEndpoint? arg_endpoint = (args[0] as BarcodeScannerEndpoint?);
          try {
            api.onActiveBarcodeScannerChanged(arg_endpoint);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onScannerConnectionStatusChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onScannerConnectionStatusChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ScannerConnectionStatus? arg_status = (args[0] as ScannerConnectionStatus?);
          assert(arg_status != null,
              'Argument for dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onScannerConnectionStatusChanged was null, expected non-null ScannerConnectionStatus.');
          try {
            api.onScannerConnectionStatusChanged(arg_status!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onBarcodeRead$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onBarcodeRead was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Barcode? arg_barcode = (args[0] as Barcode?);
          assert(arg_barcode != null,
              'Argument for dev.flutter.pigeon.flutter_zebra_barcode.FlutterZebraBarcodeCallbacks.onBarcodeRead was null, expected non-null Barcode.');
          try {
            api.onBarcodeRead(arg_barcode!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
